// 10k word/phrase expansion for Bašh lexicon.
// Focuses on: travel survival, directions, food, accommodation, emergency,
// nature, culture, body, time, numbers — for foreigners visiting KPK/GB.
// Writes directly to Supabase. Safe to re-run (upsert).
//
// Run: node server/scripts/seed_10k_expansion.js

require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY,
  { auth: { persistSession: false } }
);

function slug(en) {
  return en.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}

// [english, pos, category, type, frequency_rank]
const RAW = [

  // ═══════════════════════════════════════════════════════════════════════
  // TRAVEL GREETINGS & SOCIAL  rank 2100–2200
  // ═══════════════════════════════════════════════════════════════════════
  ['hello', 'interjection', 'greetings', 'word', 2100],
  ['goodbye', 'interjection', 'greetings', 'word', 2101],
  ['good morning', 'phrase', 'greetings', 'phrase', 2102],
  ['good afternoon', 'phrase', 'greetings', 'phrase', 2103],
  ['good evening', 'phrase', 'greetings', 'phrase', 2104],
  ['good night', 'phrase', 'greetings', 'phrase', 2105],
  ['welcome', 'interjection', 'greetings', 'word', 2106],
  ['peace be upon you', 'phrase', 'greetings', 'phrase', 2107],
  ['and upon you peace', 'phrase', 'greetings', 'phrase', 2108],
  ['how are you', 'phrase', 'greetings', 'phrase', 2109],
  ['i am fine', 'phrase', 'greetings', 'phrase', 2110],
  ['i am not well', 'phrase', 'greetings', 'phrase', 2111],
  ['nice to meet you', 'phrase', 'greetings', 'phrase', 2112],
  ['what is your name', 'phrase', 'greetings', 'phrase', 2113],
  ['my name is', 'phrase', 'greetings', 'phrase', 2114],
  ['where are you from', 'phrase', 'greetings', 'phrase', 2115],
  ['i am from', 'phrase', 'greetings', 'phrase', 2116],
  ['how old are you', 'phrase', 'greetings', 'phrase', 2117],
  ['see you later', 'phrase', 'greetings', 'phrase', 2118],
  ['see you tomorrow', 'phrase', 'greetings', 'phrase', 2119],
  ['take care', 'phrase', 'greetings', 'phrase', 2120],
  ['have a safe journey', 'phrase', 'greetings', 'phrase', 2121],
  ['blessings on you', 'phrase', 'greetings', 'phrase', 2122],
  ['congratulations', 'interjection', 'greetings', 'word', 2123],
  ['happy eid', 'phrase', 'greetings', 'phrase', 2124],

  // ═══════════════════════════════════════════════════════════════════════
  // POLITENESS & BASICS  rank 2200–2260
  // ═══════════════════════════════════════════════════════════════════════
  ['please', 'adverb', 'politeness', 'word', 2200],
  ['thank you', 'phrase', 'politeness', 'phrase', 2201],
  ['thank you very much', 'phrase', 'politeness', 'phrase', 2202],
  ['you are welcome', 'phrase', 'politeness', 'phrase', 2203],
  ['sorry', 'interjection', 'politeness', 'word', 2204],
  ['excuse me', 'phrase', 'politeness', 'phrase', 2205],
  ['no problem', 'phrase', 'politeness', 'phrase', 2206],
  ['it is okay', 'phrase', 'politeness', 'phrase', 2207],
  ['of course', 'adverb', 'politeness', 'word', 2208],
  ['yes', 'particle', 'politeness', 'word', 2209],
  ['no', 'particle', 'politeness', 'word', 2210],
  ['maybe', 'adverb', 'politeness', 'word', 2211],
  ['i agree', 'phrase', 'politeness', 'phrase', 2212],
  ['i disagree', 'phrase', 'politeness', 'phrase', 2213],
  ['can you help me', 'phrase', 'politeness', 'phrase', 2214],
  ['i need help', 'phrase', 'politeness', 'phrase', 2215],
  ['wait a moment', 'phrase', 'politeness', 'phrase', 2216],
  ['i do not understand', 'phrase', 'politeness', 'phrase', 2217],
  ['please repeat that', 'phrase', 'politeness', 'phrase', 2218],
  ['speak slowly please', 'phrase', 'politeness', 'phrase', 2219],
  ['do you speak english', 'phrase', 'politeness', 'phrase', 2220],
  ['i speak a little', 'phrase', 'politeness', 'phrase', 2221],
  ['how do you say this', 'phrase', 'politeness', 'phrase', 2222],
  ['what does this mean', 'phrase', 'politeness', 'phrase', 2223],
  ['can you write it down', 'phrase', 'politeness', 'phrase', 2224],

  // ═══════════════════════════════════════════════════════════════════════
  // ASKING DIRECTIONS  rank 2300–2420
  // ═══════════════════════════════════════════════════════════════════════
  ['where is', 'phrase', 'directions', 'phrase', 2300],
  ['how do i get to', 'phrase', 'directions', 'phrase', 2301],
  ['how far is it', 'phrase', 'directions', 'phrase', 2302],
  ['is it far', 'phrase', 'directions', 'phrase', 2303],
  ['is it near', 'phrase', 'directions', 'phrase', 2304],
  ['turn left', 'phrase', 'directions', 'phrase', 2305],
  ['turn right', 'phrase', 'directions', 'phrase', 2306],
  ['go straight', 'phrase', 'directions', 'phrase', 2307],
  ['go back', 'phrase', 'directions', 'phrase', 2308],
  ['at the end of the road', 'phrase', 'directions', 'phrase', 2309],
  ['next to', 'phrase', 'directions', 'phrase', 2310],
  ['opposite', 'adverb', 'directions', 'word', 2311],
  ['behind', 'adverb', 'directions', 'word', 2312],
  ['in front of', 'phrase', 'directions', 'phrase', 2313],
  ['on the left', 'phrase', 'directions', 'phrase', 2314],
  ['on the right', 'phrase', 'directions', 'phrase', 2315],
  ['uphill', 'adverb', 'directions', 'word', 2316],
  ['downhill', 'adverb', 'directions', 'word', 2317],
  ['across the river', 'phrase', 'directions', 'phrase', 2318],
  ['over the bridge', 'phrase', 'directions', 'phrase', 2319],
  ['through the village', 'phrase', 'directions', 'phrase', 2320],
  ['follow the path', 'phrase', 'directions', 'phrase', 2321],
  ['i am lost', 'phrase', 'directions', 'phrase', 2322],
  ['can you show me on the map', 'phrase', 'directions', 'phrase', 2323],
  ['how many hours walking', 'phrase', 'directions', 'phrase', 2324],
  ['how many kilometers', 'phrase', 'directions', 'phrase', 2325],
  ['left', 'noun', 'directions', 'word', 2326],
  ['right', 'noun', 'directions', 'word', 2327],
  ['north', 'noun', 'directions', 'word', 2328],
  ['south', 'noun', 'directions', 'word', 2329],
  ['east', 'noun', 'directions', 'word', 2330],
  ['west', 'noun', 'directions', 'word', 2331],
  ['near', 'adjective', 'directions', 'word', 2332],
  ['far', 'adjective', 'directions', 'word', 2333],
  ['here', 'adverb', 'directions', 'word', 2334],
  ['there', 'adverb', 'directions', 'word', 2335],
  ['this way', 'phrase', 'directions', 'phrase', 2336],
  ['that way', 'phrase', 'directions', 'phrase', 2337],
  ['map', 'noun', 'directions', 'word', 2338],
  ['path', 'noun', 'directions', 'word', 2339],
  ['trail', 'noun', 'directions', 'word', 2340],
  ['road', 'noun', 'directions', 'word', 2341],
  ['street', 'noun', 'directions', 'word', 2342],
  ['bridge', 'noun', 'directions', 'word', 2343],
  ['crossroads', 'noun', 'directions', 'word', 2344],
  ['junction', 'noun', 'directions', 'word', 2345],
  ['checkpoint', 'noun', 'directions', 'word', 2346],
  ['border', 'noun', 'directions', 'word', 2347],

  // ═══════════════════════════════════════════════════════════════════════
  // ACCOMMODATION  rank 2400–2500
  // ═══════════════════════════════════════════════════════════════════════
  ['hotel', 'noun', 'accommodation', 'word', 2400],
  ['guesthouse', 'noun', 'accommodation', 'word', 2401],
  ['room', 'noun', 'accommodation', 'word', 2402],
  ['do you have a room', 'phrase', 'accommodation', 'phrase', 2403],
  ['how much per night', 'phrase', 'accommodation', 'phrase', 2404],
  ['i have a reservation', 'phrase', 'accommodation', 'phrase', 2405],
  ['i want to check in', 'phrase', 'accommodation', 'phrase', 2406],
  ['i want to check out', 'phrase', 'accommodation', 'phrase', 2407],
  ['bed', 'noun', 'accommodation', 'word', 2408],
  ['pillow', 'noun', 'accommodation', 'word', 2409],
  ['blanket', 'noun', 'accommodation', 'word', 2410],
  ['bathroom', 'noun', 'accommodation', 'word', 2411],
  ['toilet', 'noun', 'accommodation', 'word', 2412],
  ['shower', 'noun', 'accommodation', 'word', 2413],
  ['hot water', 'phrase', 'accommodation', 'phrase', 2414],
  ['cold water', 'phrase', 'accommodation', 'phrase', 2415],
  ['electricity', 'noun', 'accommodation', 'word', 2416],
  ['key', 'noun', 'accommodation', 'word', 2417],
  ['lock', 'noun', 'accommodation', 'word', 2418],
  ['window', 'noun', 'accommodation', 'word', 2419],
  ['door', 'noun', 'accommodation', 'word', 2420],
  ['is breakfast included', 'phrase', 'accommodation', 'phrase', 2421],
  ['can i see the room', 'phrase', 'accommodation', 'phrase', 2422],
  ['the room is dirty', 'phrase', 'accommodation', 'phrase', 2423],
  ['the room is cold', 'phrase', 'accommodation', 'phrase', 2424],
  ['i need another blanket', 'phrase', 'accommodation', 'phrase', 2425],
  ['where is the bathroom', 'phrase', 'accommodation', 'phrase', 2426],
  ['camping', 'noun', 'accommodation', 'word', 2427],
  ['tent', 'noun', 'accommodation', 'word', 2428],
  ['sleeping bag', 'phrase', 'accommodation', 'phrase', 2429],
  ['can i camp here', 'phrase', 'accommodation', 'phrase', 2430],

  // ═══════════════════════════════════════════════════════════════════════
  // FOOD & EATING  rank 2500–2650
  // ═══════════════════════════════════════════════════════════════════════
  ['restaurant', 'noun', 'food', 'word', 2500],
  ['food', 'noun', 'food', 'word', 2501],
  ['i am hungry', 'phrase', 'food', 'phrase', 2502],
  ['i am thirsty', 'phrase', 'food', 'phrase', 2503],
  ['i want to eat', 'phrase', 'food', 'phrase', 2504],
  ['i want to drink', 'phrase', 'food', 'phrase', 2505],
  ['what do you have', 'phrase', 'food', 'phrase', 2506],
  ['what is this dish', 'phrase', 'food', 'phrase', 2507],
  ['bring me the menu', 'phrase', 'food', 'phrase', 2508],
  ['i want to order', 'phrase', 'food', 'phrase', 2509],
  ['the bill please', 'phrase', 'food', 'phrase', 2510],
  ['it is delicious', 'phrase', 'food', 'phrase', 2511],
  ['it is too spicy', 'phrase', 'food', 'phrase', 2512],
  ['not spicy please', 'phrase', 'food', 'phrase', 2513],
  ['i am vegetarian', 'phrase', 'food', 'phrase', 2514],
  ['i am full', 'phrase', 'food', 'phrase', 2515],
  ['i am allergic to', 'phrase', 'food', 'phrase', 2516],
  ['water', 'noun', 'food', 'word', 2517],
  ['tea', 'noun', 'food', 'word', 2518],
  ['green tea', 'phrase', 'food', 'phrase', 2519],
  ['milk tea', 'phrase', 'food', 'phrase', 2520],
  ['salt tea', 'phrase', 'food', 'phrase', 2521],
  ['coffee', 'noun', 'food', 'word', 2522],
  ['milk', 'noun', 'food', 'word', 2523],
  ['bread', 'noun', 'food', 'word', 2524],
  ['flatbread', 'noun', 'food', 'word', 2525],
  ['rice', 'noun', 'food', 'word', 2526],
  ['meat', 'noun', 'food', 'word', 2527],
  ['chicken', 'noun', 'food', 'word', 2528],
  ['lamb', 'noun', 'food', 'word', 2529],
  ['beef', 'noun', 'food', 'word', 2530],
  ['fish', 'noun', 'food', 'word', 2531],
  ['egg', 'noun', 'food', 'word', 2532],
  ['vegetable', 'noun', 'food', 'word', 2533],
  ['onion', 'noun', 'food', 'word', 2534],
  ['tomato', 'noun', 'food', 'word', 2535],
  ['potato', 'noun', 'food', 'word', 2536],
  ['garlic', 'noun', 'food', 'word', 2537],
  ['ginger', 'noun', 'food', 'word', 2538],
  ['spinach', 'noun', 'food', 'word', 2539],
  ['lentil', 'noun', 'food', 'word', 2540],
  ['fruit', 'noun', 'food', 'word', 2541],
  ['apple', 'noun', 'food', 'word', 2542],
  ['apricot', 'noun', 'food', 'word', 2543],
  ['mulberry', 'noun', 'food', 'word', 2544],
  ['walnut', 'noun', 'food', 'word', 2545],
  ['pomegranate', 'noun', 'food', 'word', 2546],
  ['cherry', 'noun', 'food', 'word', 2547],
  ['grape', 'noun', 'food', 'word', 2548],
  ['salt', 'noun', 'food', 'word', 2549],
  ['sugar', 'noun', 'food', 'word', 2550],
  ['oil', 'noun', 'food', 'word', 2551],
  ['butter', 'noun', 'food', 'word', 2552],
  ['honey', 'noun', 'food', 'word', 2553],
  ['yogurt', 'noun', 'food', 'word', 2554],
  ['cheese', 'noun', 'food', 'word', 2555],
  ['soup', 'noun', 'food', 'word', 2556],
  ['breakfast', 'noun', 'food', 'word', 2557],
  ['lunch', 'noun', 'food', 'word', 2558],
  ['dinner', 'noun', 'food', 'word', 2559],
  ['snack', 'noun', 'food', 'word', 2560],
  ['plate', 'noun', 'food', 'word', 2561],
  ['cup', 'noun', 'food', 'word', 2562],
  ['spoon', 'noun', 'food', 'word', 2563],
  ['cooked', 'adjective', 'food', 'word', 2564],
  ['raw', 'adjective', 'food', 'word', 2565],
  ['fresh', 'adjective', 'food', 'word', 2566],
  ['dried apricot', 'phrase', 'food', 'phrase', 2567],
  ['dried fruit', 'phrase', 'food', 'phrase', 2568],
  ['local food', 'phrase', 'food', 'phrase', 2569],
  ['traditional dish', 'phrase', 'food', 'phrase', 2570],

  // ═══════════════════════════════════════════════════════════════════════
  // TRANSPORTATION  rank 2650–2780
  // ═══════════════════════════════════════════════════════════════════════
  ['bus', 'noun', 'transport', 'word', 2650],
  ['jeep', 'noun', 'transport', 'word', 2651],
  ['car', 'noun', 'transport', 'word', 2652],
  ['truck', 'noun', 'transport', 'word', 2653],
  ['motorcycle', 'noun', 'transport', 'word', 2654],
  ['bicycle', 'noun', 'transport', 'word', 2655],
  ['horse', 'noun', 'transport', 'word', 2656],
  ['donkey', 'noun', 'transport', 'word', 2657],
  ['porter', 'noun', 'transport', 'word', 2658],
  ['guide', 'noun', 'transport', 'word', 2659],
  ['driver', 'noun', 'transport', 'word', 2660],
  ['bus station', 'phrase', 'transport', 'phrase', 2661],
  ['when does the bus leave', 'phrase', 'transport', 'phrase', 2662],
  ['where does this bus go', 'phrase', 'transport', 'phrase', 2663],
  ['how much is the ticket', 'phrase', 'transport', 'phrase', 2664],
  ['one ticket to', 'phrase', 'transport', 'phrase', 2665],
  ['stop here please', 'phrase', 'transport', 'phrase', 2666],
  ['i want to go to', 'phrase', 'transport', 'phrase', 2667],
  ['how long does it take', 'phrase', 'transport', 'phrase', 2668],
  ['is the road open', 'phrase', 'transport', 'phrase', 2669],
  ['the road is blocked', 'phrase', 'transport', 'phrase', 2670],
  ['landslide', 'noun', 'transport', 'word', 2671],
  ['petrol station', 'phrase', 'transport', 'phrase', 2672],
  ['airport', 'noun', 'transport', 'word', 2673],
  ['helicopter', 'noun', 'transport', 'word', 2674],
  ['passport', 'noun', 'transport', 'word', 2675],
  ['permit', 'noun', 'transport', 'word', 2676],
  ['luggage', 'noun', 'transport', 'word', 2677],
  ['backpack', 'noun', 'transport', 'word', 2678],
  ['ticket', 'noun', 'transport', 'word', 2679],

  // ═══════════════════════════════════════════════════════════════════════
  // SHOPPING & MONEY  rank 2780–2870
  // ═══════════════════════════════════════════════════════════════════════
  ['market', 'noun', 'shopping', 'word', 2780],
  ['bazaar', 'noun', 'shopping', 'word', 2781],
  ['shop', 'noun', 'shopping', 'word', 2782],
  ['how much does this cost', 'phrase', 'shopping', 'phrase', 2783],
  ['it is too expensive', 'phrase', 'shopping', 'phrase', 2784],
  ['can you lower the price', 'phrase', 'shopping', 'phrase', 2785],
  ['i want to buy this', 'phrase', 'shopping', 'phrase', 2786],
  ['i do not want this', 'phrase', 'shopping', 'phrase', 2787],
  ['do you have', 'phrase', 'shopping', 'phrase', 2788],
  ['give me two of these', 'phrase', 'shopping', 'phrase', 2789],
  ['money', 'noun', 'shopping', 'word', 2790],
  ['price', 'noun', 'shopping', 'word', 2791],
  ['change', 'noun', 'shopping', 'word', 2792],
  ['receipt', 'noun', 'shopping', 'word', 2793],
  ['expensive', 'adjective', 'shopping', 'word', 2794],
  ['cheap', 'adjective', 'shopping', 'word', 2795],
  ['discount', 'noun', 'shopping', 'word', 2796],
  ['fixed price', 'phrase', 'shopping', 'phrase', 2797],
  ['i am just looking', 'phrase', 'shopping', 'phrase', 2798],
  ['can i try this', 'phrase', 'shopping', 'phrase', 2799],
  ['what is this made of', 'phrase', 'shopping', 'phrase', 2800],
  ['bank', 'noun', 'shopping', 'word', 2801],
  ['exchange', 'noun', 'shopping', 'word', 2802],
  ['atm', 'noun', 'shopping', 'word', 2803],

  // ═══════════════════════════════════════════════════════════════════════
  // EMERGENCY & HEALTH  rank 2870–2980
  // ═══════════════════════════════════════════════════════════════════════
  ['help', 'interjection', 'emergency', 'word', 2870],
  ['emergency', 'noun', 'emergency', 'word', 2871],
  ['danger', 'noun', 'emergency', 'word', 2872],
  ['be careful', 'phrase', 'emergency', 'phrase', 2873],
  ['stop', 'interjection', 'emergency', 'word', 2874],
  ['call the police', 'phrase', 'emergency', 'phrase', 2875],
  ['call an ambulance', 'phrase', 'emergency', 'phrase', 2876],
  ['i need a doctor', 'phrase', 'emergency', 'phrase', 2877],
  ['where is the hospital', 'phrase', 'emergency', 'phrase', 2878],
  ['where is the nearest village', 'phrase', 'emergency', 'phrase', 2879],
  ['i am injured', 'phrase', 'emergency', 'phrase', 2880],
  ['i am sick', 'phrase', 'emergency', 'phrase', 2881],
  ['i have altitude sickness', 'phrase', 'emergency', 'phrase', 2882],
  ['i cannot breathe', 'phrase', 'emergency', 'phrase', 2883],
  ['i have a headache', 'phrase', 'emergency', 'phrase', 2884],
  ['i have a fever', 'phrase', 'emergency', 'phrase', 2885],
  ['i have diarrhea', 'phrase', 'emergency', 'phrase', 2886],
  ['i have a stomach ache', 'phrase', 'emergency', 'phrase', 2887],
  ['my leg is broken', 'phrase', 'emergency', 'phrase', 2888],
  ['i need medicine', 'phrase', 'emergency', 'phrase', 2889],
  ['pharmacy', 'noun', 'emergency', 'word', 2890],
  ['hospital', 'noun', 'emergency', 'word', 2891],
  ['police', 'noun', 'emergency', 'word', 2892],
  ['fire', 'noun', 'emergency', 'word', 2893],
  ['flood', 'noun', 'emergency', 'word', 2894],
  ['avalanche', 'noun', 'emergency', 'word', 2895],
  ['earthquake', 'noun', 'emergency', 'word', 2896],
  ['there is a fire', 'phrase', 'emergency', 'phrase', 2897],
  ['there has been an accident', 'phrase', 'emergency', 'phrase', 2898],
  ['i need water urgently', 'phrase', 'emergency', 'phrase', 2899],
  ['pain', 'noun', 'emergency', 'word', 2900],
  ['blood', 'noun', 'emergency', 'word', 2901],
  ['broken', 'adjective', 'emergency', 'word', 2902],
  ['medicine', 'noun', 'emergency', 'word', 2903],
  ['bandage', 'noun', 'emergency', 'word', 2904],
  ['tablet', 'noun', 'emergency', 'word', 2905],
  ['i am diabetic', 'phrase', 'emergency', 'phrase', 2906],
  ['i am allergic to this', 'phrase', 'emergency', 'phrase', 2907],
  ['search and rescue', 'phrase', 'emergency', 'phrase', 2908],

  // ═══════════════════════════════════════════════════════════════════════
  // NUMBERS  rank 3000–3060
  // ═══════════════════════════════════════════════════════════════════════
  ['zero', 'number', 'numbers', 'word', 3000],
  ['one', 'number', 'numbers', 'word', 3001],
  ['two', 'number', 'numbers', 'word', 3002],
  ['three', 'number', 'numbers', 'word', 3003],
  ['four', 'number', 'numbers', 'word', 3004],
  ['five', 'number', 'numbers', 'word', 3005],
  ['six', 'number', 'numbers', 'word', 3006],
  ['seven', 'number', 'numbers', 'word', 3007],
  ['eight', 'number', 'numbers', 'word', 3008],
  ['nine', 'number', 'numbers', 'word', 3009],
  ['ten', 'number', 'numbers', 'word', 3010],
  ['eleven', 'number', 'numbers', 'word', 3011],
  ['twelve', 'number', 'numbers', 'word', 3012],
  ['thirteen', 'number', 'numbers', 'word', 3013],
  ['fourteen', 'number', 'numbers', 'word', 3014],
  ['fifteen', 'number', 'numbers', 'word', 3015],
  ['sixteen', 'number', 'numbers', 'word', 3016],
  ['seventeen', 'number', 'numbers', 'word', 3017],
  ['eighteen', 'number', 'numbers', 'word', 3018],
  ['nineteen', 'number', 'numbers', 'word', 3019],
  ['twenty', 'number', 'numbers', 'word', 3020],
  ['thirty', 'number', 'numbers', 'word', 3021],
  ['forty', 'number', 'numbers', 'word', 3022],
  ['fifty', 'number', 'numbers', 'word', 3023],
  ['sixty', 'number', 'numbers', 'word', 3024],
  ['seventy', 'number', 'numbers', 'word', 3025],
  ['eighty', 'number', 'numbers', 'word', 3026],
  ['ninety', 'number', 'numbers', 'word', 3027],
  ['one hundred', 'number', 'numbers', 'word', 3028],
  ['one thousand', 'number', 'numbers', 'word', 3029],
  ['half', 'number', 'numbers', 'word', 3030],
  ['quarter', 'number', 'numbers', 'word', 3031],
  ['first', 'number', 'numbers', 'word', 3032],
  ['second', 'number', 'numbers', 'word', 3033],
  ['third', 'number', 'numbers', 'word', 3034],
  ['last', 'adjective', 'numbers', 'word', 3035],
  ['next', 'adjective', 'numbers', 'word', 3036],

  // ═══════════════════════════════════════════════════════════════════════
  // TIME & DATES  rank 3100–3200
  // ═══════════════════════════════════════════════════════════════════════
  ['now', 'adverb', 'time', 'word', 3100],
  ['later', 'adverb', 'time', 'word', 3101],
  ['soon', 'adverb', 'time', 'word', 3102],
  ['today', 'adverb', 'time', 'word', 3103],
  ['tomorrow', 'adverb', 'time', 'word', 3104],
  ['yesterday', 'adverb', 'time', 'word', 3105],
  ['morning', 'noun', 'time', 'word', 3106],
  ['afternoon', 'noun', 'time', 'word', 3107],
  ['evening', 'noun', 'time', 'word', 3108],
  ['night', 'noun', 'time', 'word', 3109],
  ['midnight', 'noun', 'time', 'word', 3110],
  ['dawn', 'noun', 'time', 'word', 3111],
  ['what time is it', 'phrase', 'time', 'phrase', 3112],
  ['when', 'adverb', 'time', 'word', 3113],
  ['hour', 'noun', 'time', 'word', 3114],
  ['minute', 'noun', 'time', 'word', 3115],
  ['day', 'noun', 'time', 'word', 3116],
  ['week', 'noun', 'time', 'word', 3117],
  ['month', 'noun', 'time', 'word', 3118],
  ['year', 'noun', 'time', 'word', 3119],
  ['monday', 'noun', 'time', 'word', 3120],
  ['tuesday', 'noun', 'time', 'word', 3121],
  ['wednesday', 'noun', 'time', 'word', 3122],
  ['thursday', 'noun', 'time', 'word', 3123],
  ['friday', 'noun', 'time', 'word', 3124],
  ['saturday', 'noun', 'time', 'word', 3125],
  ['sunday', 'noun', 'time', 'word', 3126],
  ['january', 'noun', 'time', 'word', 3127],
  ['february', 'noun', 'time', 'word', 3128],
  ['march', 'noun', 'time', 'word', 3129],
  ['april', 'noun', 'time', 'word', 3130],
  ['may', 'noun', 'time', 'word', 3131],
  ['june', 'noun', 'time', 'word', 3132],
  ['july', 'noun', 'time', 'word', 3133],
  ['august', 'noun', 'time', 'word', 3134],
  ['september', 'noun', 'time', 'word', 3135],
  ['october', 'noun', 'time', 'word', 3136],
  ['november', 'noun', 'time', 'word', 3137],
  ['december', 'noun', 'time', 'word', 3138],
  ['spring', 'noun', 'time', 'word', 3139],
  ['summer', 'noun', 'time', 'word', 3140],
  ['autumn', 'noun', 'time', 'word', 3141],
  ['winter', 'noun', 'time', 'word', 3142],
  ['early', 'adverb', 'time', 'word', 3143],
  ['late', 'adverb', 'time', 'word', 3144],
  ['on time', 'phrase', 'time', 'phrase', 3145],

  // ═══════════════════════════════════════════════════════════════════════
  // WEATHER (critical for mountain travelers)  rank 3200–3290
  // ═══════════════════════════════════════════════════════════════════════
  ['rain', 'noun', 'weather', 'word', 3200],
  ['snow', 'noun', 'weather', 'word', 3201],
  ['sun', 'noun', 'weather', 'word', 3202],
  ['cloud', 'noun', 'weather', 'word', 3203],
  ['wind', 'noun', 'weather', 'word', 3204],
  ['storm', 'noun', 'weather', 'word', 3205],
  ['fog', 'noun', 'weather', 'word', 3206],
  ['ice', 'noun', 'weather', 'word', 3207],
  ['frost', 'noun', 'weather', 'word', 3208],
  ['thunder', 'noun', 'weather', 'word', 3209],
  ['lightning', 'noun', 'weather', 'word', 3210],
  ['it is raining', 'phrase', 'weather', 'phrase', 3211],
  ['it is snowing', 'phrase', 'weather', 'phrase', 3212],
  ['it is cold', 'phrase', 'weather', 'phrase', 3213],
  ['it is hot', 'phrase', 'weather', 'phrase', 3214],
  ['the weather is good', 'phrase', 'weather', 'phrase', 3215],
  ['the weather is bad', 'phrase', 'weather', 'phrase', 3216],
  ['will it rain today', 'phrase', 'weather', 'phrase', 3217],
  ['will the road be open', 'phrase', 'weather', 'phrase', 3218],
  ['heavy snowfall', 'phrase', 'weather', 'phrase', 3219],
  ['strong wind', 'phrase', 'weather', 'phrase', 3220],
  ['dry', 'adjective', 'weather', 'word', 3221],
  ['wet', 'adjective', 'weather', 'word', 3222],
  ['clear sky', 'phrase', 'weather', 'phrase', 3223],
  ['cloudy', 'adjective', 'weather', 'word', 3224],
  ['sunny', 'adjective', 'weather', 'word', 3225],
  ['freezing', 'adjective', 'weather', 'word', 3226],
  ['temperature', 'noun', 'weather', 'word', 3227],
  ['forecast', 'noun', 'weather', 'word', 3228],

  // ═══════════════════════════════════════════════════════════════════════
  // NATURE & MOUNTAINS  rank 3300–3450
  // ═══════════════════════════════════════════════════════════════════════
  ['mountain', 'noun', 'nature', 'word', 3300],
  ['peak', 'noun', 'nature', 'word', 3301],
  ['summit', 'noun', 'nature', 'word', 3302],
  ['glacier', 'noun', 'nature', 'word', 3303],
  ['valley', 'noun', 'nature', 'word', 3304],
  ['river', 'noun', 'nature', 'word', 3305],
  ['stream', 'noun', 'nature', 'word', 3306],
  ['lake', 'noun', 'nature', 'word', 3307],
  ['waterfall', 'noun', 'nature', 'word', 3308],
  ['spring water', 'phrase', 'nature', 'phrase', 3309],
  ['cliff', 'noun', 'nature', 'word', 3310],
  ['rock', 'noun', 'nature', 'word', 3311],
  ['stone', 'noun', 'nature', 'word', 3312],
  ['sand', 'noun', 'nature', 'word', 3313],
  ['soil', 'noun', 'nature', 'word', 3314],
  ['meadow', 'noun', 'nature', 'word', 3315],
  ['forest', 'noun', 'nature', 'word', 3316],
  ['desert', 'noun', 'nature', 'word', 3317],
  ['sky', 'noun', 'nature', 'word', 3318],
  ['stars', 'noun', 'nature', 'word', 3319],
  ['moon', 'noun', 'nature', 'word', 3320],
  ['sunrise', 'noun', 'nature', 'word', 3321],
  ['sunset', 'noun', 'nature', 'word', 3322],
  ['tree', 'noun', 'nature', 'word', 3323],
  ['flower', 'noun', 'nature', 'word', 3324],
  ['grass', 'noun', 'nature', 'word', 3325],
  ['bush', 'noun', 'nature', 'word', 3326],
  ['willow', 'noun', 'nature', 'word', 3327],
  ['poplar', 'noun', 'nature', 'word', 3328],
  ['juniper', 'noun', 'nature', 'word', 3329],
  ['snow leopard', 'phrase', 'nature', 'phrase', 3330],
  ['ibex', 'noun', 'nature', 'word', 3331],
  ['markhor', 'noun', 'nature', 'word', 3332],
  ['bear', 'noun', 'nature', 'word', 3333],
  ['wolf', 'noun', 'nature', 'word', 3334],
  ['eagle', 'noun', 'nature', 'word', 3335],
  ['vulture', 'noun', 'nature', 'word', 3336],
  ['yak', 'noun', 'nature', 'word', 3337],
  ['sheep', 'noun', 'nature', 'word', 3338],
  ['goat', 'noun', 'nature', 'word', 3339],
  ['cow', 'noun', 'nature', 'word', 3340],
  ['dog', 'noun', 'nature', 'word', 3341],
  ['cat', 'noun', 'nature', 'word', 3342],
  ['bird', 'noun', 'nature', 'word', 3343],
  ['fish', 'noun', 'nature', 'word', 3344],
  ['snake', 'noun', 'nature', 'word', 3345],
  ['insect', 'noun', 'nature', 'word', 3346],
  ['the mountains are beautiful', 'phrase', 'nature', 'phrase', 3347],
  ['how high is this mountain', 'phrase', 'nature', 'phrase', 3348],
  ['is this water safe to drink', 'phrase', 'nature', 'phrase', 3349],
  ['where is the nearest water source', 'phrase', 'nature', 'phrase', 3350],

  // ═══════════════════════════════════════════════════════════════════════
  // BODY PARTS & HEALTH  rank 3450–3550
  // ═══════════════════════════════════════════════════════════════════════
  ['head', 'noun', 'body', 'word', 3450],
  ['hair', 'noun', 'body', 'word', 3451],
  ['eye', 'noun', 'body', 'word', 3452],
  ['ear', 'noun', 'body', 'word', 3453],
  ['nose', 'noun', 'body', 'word', 3454],
  ['mouth', 'noun', 'body', 'word', 3455],
  ['teeth', 'noun', 'body', 'word', 3456],
  ['tongue', 'noun', 'body', 'word', 3457],
  ['neck', 'noun', 'body', 'word', 3458],
  ['shoulder', 'noun', 'body', 'word', 3459],
  ['arm', 'noun', 'body', 'word', 3460],
  ['hand', 'noun', 'body', 'word', 3461],
  ['finger', 'noun', 'body', 'word', 3462],
  ['chest', 'noun', 'body', 'word', 3463],
  ['back', 'noun', 'body', 'word', 3464],
  ['stomach', 'noun', 'body', 'word', 3465],
  ['leg', 'noun', 'body', 'word', 3466],
  ['knee', 'noun', 'body', 'word', 3467],
  ['foot', 'noun', 'body', 'word', 3468],
  ['skin', 'noun', 'body', 'word', 3469],
  ['bone', 'noun', 'body', 'word', 3470],
  ['heart', 'noun', 'body', 'word', 3471],
  ['it hurts here', 'phrase', 'body', 'phrase', 3472],
  ['my head hurts', 'phrase', 'body', 'phrase', 3473],
  ['my stomach hurts', 'phrase', 'body', 'phrase', 3474],
  ['my leg hurts', 'phrase', 'body', 'phrase', 3475],
  ['i cannot walk', 'phrase', 'body', 'phrase', 3476],
  ['fever', 'noun', 'body', 'word', 3477],
  ['cough', 'noun', 'body', 'word', 3478],
  ['cold', 'noun', 'body', 'word', 3479],
  ['dizzy', 'adjective', 'body', 'word', 3480],
  ['tired', 'adjective', 'body', 'word', 3481],
  ['weak', 'adjective', 'body', 'word', 3482],
  ['vomiting', 'noun', 'body', 'word', 3483],
  ['bleeding', 'noun', 'body', 'word', 3484],

  // ═══════════════════════════════════════════════════════════════════════
  // FAMILY & PEOPLE  rank 3550–3650
  // ═══════════════════════════════════════════════════════════════════════
  ['mother', 'noun', 'family', 'word', 3550],
  ['father', 'noun', 'family', 'word', 3551],
  ['son', 'noun', 'family', 'word', 3552],
  ['daughter', 'noun', 'family', 'word', 3553],
  ['brother', 'noun', 'family', 'word', 3554],
  ['sister', 'noun', 'family', 'word', 3555],
  ['husband', 'noun', 'family', 'word', 3556],
  ['wife', 'noun', 'family', 'word', 3557],
  ['child', 'noun', 'family', 'word', 3558],
  ['baby', 'noun', 'family', 'word', 3559],
  ['grandfather', 'noun', 'family', 'word', 3560],
  ['grandmother', 'noun', 'family', 'word', 3561],
  ['uncle', 'noun', 'family', 'word', 3562],
  ['aunt', 'noun', 'family', 'word', 3563],
  ['cousin', 'noun', 'family', 'word', 3564],
  ['friend', 'noun', 'family', 'word', 3565],
  ['neighbor', 'noun', 'family', 'word', 3566],
  ['host', 'noun', 'family', 'word', 3567],
  ['guest', 'noun', 'family', 'word', 3568],
  ['elder', 'noun', 'family', 'word', 3569],
  ['man', 'noun', 'family', 'word', 3570],
  ['woman', 'noun', 'family', 'word', 3571],
  ['boy', 'noun', 'family', 'word', 3572],
  ['girl', 'noun', 'family', 'word', 3573],
  ['young', 'adjective', 'family', 'word', 3574],
  ['old', 'adjective', 'family', 'word', 3575],
  ['family', 'noun', 'family', 'word', 3576],
  ['people', 'noun', 'family', 'word', 3577],
  ['stranger', 'noun', 'family', 'word', 3578],
  ['tourist', 'noun', 'family', 'word', 3579],
  ['traveler', 'noun', 'family', 'word', 3580],
  ['foreigner', 'noun', 'family', 'word', 3581],

  // ═══════════════════════════════════════════════════════════════════════
  // CULTURE & RELIGION  rank 3650–3750
  // ═══════════════════════════════════════════════════════════════════════
  ['mosque', 'noun', 'culture', 'word', 3650],
  ['prayer', 'noun', 'culture', 'word', 3651],
  ['fast', 'noun', 'culture', 'word', 3652],
  ['ramadan', 'noun', 'culture', 'word', 3653],
  ['eid', 'noun', 'culture', 'word', 3654],
  ['shrine', 'noun', 'culture', 'word', 3655],
  ['festival', 'noun', 'culture', 'word', 3656],
  ['tradition', 'noun', 'culture', 'word', 3657],
  ['custom', 'noun', 'culture', 'word', 3658],
  ['guest is sacred', 'phrase', 'culture', 'phrase', 3659],
  ['hospitality', 'noun', 'culture', 'word', 3660],
  ['respect', 'noun', 'culture', 'word', 3661],
  ['honor', 'noun', 'culture', 'word', 3662],
  ['elder', 'noun', 'culture', 'word', 3663],
  ['blessing', 'noun', 'culture', 'word', 3664],
  ['may god protect you', 'phrase', 'culture', 'phrase', 3665],
  ['may god bless you', 'phrase', 'culture', 'phrase', 3666],
  ['is it okay to take photos here', 'phrase', 'culture', 'phrase', 3667],
  ['can i enter the mosque', 'phrase', 'culture', 'phrase', 3668],
  ['is this halal', 'phrase', 'culture', 'phrase', 3669],
  ['music', 'noun', 'culture', 'word', 3670],
  ['song', 'noun', 'culture', 'word', 3671],
  ['dance', 'noun', 'culture', 'word', 3672],
  ['story', 'noun', 'culture', 'word', 3673],
  ['poetry', 'noun', 'culture', 'word', 3674],
  ['traditional dress', 'phrase', 'culture', 'phrase', 3675],
  ['local language', 'phrase', 'culture', 'phrase', 3676],
  ['i want to learn your language', 'phrase', 'culture', 'phrase', 3677],
  ['how do you say this in your language', 'phrase', 'culture', 'phrase', 3678],
  ['your culture is beautiful', 'phrase', 'culture', 'phrase', 3679],

  // ═══════════════════════════════════════════════════════════════════════
  // TREKKING & ADVENTURE  rank 3750–3870
  // ═══════════════════════════════════════════════════════════════════════
  ['trekking', 'noun', 'trekking', 'word', 3750],
  ['hiking', 'noun', 'trekking', 'word', 3751],
  ['base camp', 'phrase', 'trekking', 'phrase', 3752],
  ['camp', 'noun', 'trekking', 'word', 3753],
  ['altitude', 'noun', 'trekking', 'word', 3754],
  ['rope', 'noun', 'trekking', 'word', 3755],
  ['safety', 'noun', 'trekking', 'word', 3756],
  ['i am going trekking', 'phrase', 'trekking', 'phrase', 3757],
  ['i need a porter', 'phrase', 'trekking', 'phrase', 3758],
  ['i need a guide', 'phrase', 'trekking', 'phrase', 3759],
  ['how many days to reach', 'phrase', 'trekking', 'phrase', 3760],
  ['is this route safe', 'phrase', 'trekking', 'phrase', 3761],
  ['where can i fill water', 'phrase', 'trekking', 'phrase', 3762],
  ['the trail is steep', 'phrase', 'trekking', 'phrase', 3763],
  ['i need to rest', 'phrase', 'trekking', 'phrase', 3764],
  ['my feet hurt', 'phrase', 'trekking', 'phrase', 3765],
  ['is there a shelter ahead', 'phrase', 'trekking', 'phrase', 3766],
  ['how much do you charge per day', 'phrase', 'trekking', 'phrase', 3767],
  ['boots', 'noun', 'trekking', 'word', 3768],
  ['jacket', 'noun', 'trekking', 'word', 3769],
  ['gloves', 'noun', 'trekking', 'word', 3770],
  ['hat', 'noun', 'trekking', 'word', 3771],
  ['sunscreen', 'noun', 'trekking', 'word', 3772],
  ['water bottle', 'phrase', 'trekking', 'phrase', 3773],
  ['matches', 'noun', 'trekking', 'word', 3774],
  ['torch', 'noun', 'trekking', 'word', 3775],
  ['first aid', 'phrase', 'trekking', 'phrase', 3776],
  ['i want to climb this mountain', 'phrase', 'trekking', 'phrase', 3777],
  ['it is too dangerous', 'phrase', 'trekking', 'phrase', 3778],
  ['go back now', 'phrase', 'trekking', 'phrase', 3779],

  // ═══════════════════════════════════════════════════════════════════════
  // VILLAGES & PLACES  rank 3870–3960
  // ═══════════════════════════════════════════════════════════════════════
  ['village', 'noun', 'places', 'word', 3870],
  ['town', 'noun', 'places', 'word', 3871],
  ['city', 'noun', 'places', 'word', 3872],
  ['district', 'noun', 'places', 'word', 3873],
  ['valley', 'noun', 'places', 'word', 3874],
  ['where is this village', 'phrase', 'places', 'phrase', 3875],
  ['how far is the next village', 'phrase', 'places', 'phrase', 3876],
  ['is there a shop in this village', 'phrase', 'places', 'phrase', 3877],
  ['post office', 'phrase', 'places', 'phrase', 3878],
  ['school', 'noun', 'places', 'word', 3879],
  ['hospital', 'noun', 'places', 'word', 3880],
  ['clinic', 'noun', 'places', 'word', 3881],
  ['government office', 'phrase', 'places', 'phrase', 3882],
  ['police station', 'phrase', 'places', 'phrase', 3883],
  ['shrine', 'noun', 'places', 'word', 3884],
  ['orchard', 'noun', 'places', 'word', 3885],
  ['field', 'noun', 'places', 'word', 3886],
  ['pasture', 'noun', 'places', 'word', 3887],
  ['irrigation canal', 'phrase', 'places', 'phrase', 3888],
  ['terraced fields', 'phrase', 'places', 'phrase', 3889],
  ['suspension bridge', 'phrase', 'places', 'phrase', 3890],

  // ═══════════════════════════════════════════════════════════════════════
  // ADJECTIVES  rank 4000–4100
  // ═══════════════════════════════════════════════════════════════════════
  ['big', 'adjective', 'adjectives', 'word', 4000],
  ['small', 'adjective', 'adjectives', 'word', 4001],
  ['tall', 'adjective', 'adjectives', 'word', 4002],
  ['short', 'adjective', 'adjectives', 'word', 4003],
  ['long', 'adjective', 'adjectives', 'word', 4004],
  ['wide', 'adjective', 'adjectives', 'word', 4005],
  ['narrow', 'adjective', 'adjectives', 'word', 4006],
  ['heavy', 'adjective', 'adjectives', 'word', 4007],
  ['light', 'adjective', 'adjectives', 'word', 4008],
  ['fast', 'adjective', 'adjectives', 'word', 4009],
  ['slow', 'adjective', 'adjectives', 'word', 4010],
  ['good', 'adjective', 'adjectives', 'word', 4011],
  ['bad', 'adjective', 'adjectives', 'word', 4012],
  ['beautiful', 'adjective', 'adjectives', 'word', 4013],
  ['clean', 'adjective', 'adjectives', 'word', 4014],
  ['dirty', 'adjective', 'adjectives', 'word', 4015],
  ['hot', 'adjective', 'adjectives', 'word', 4016],
  ['cold', 'adjective', 'adjectives', 'word', 4017],
  ['new', 'adjective', 'adjectives', 'word', 4018],
  ['difficult', 'adjective', 'adjectives', 'word', 4019],
  ['easy', 'adjective', 'adjectives', 'word', 4020],
  ['safe', 'adjective', 'adjectives', 'word', 4021],
  ['dangerous', 'adjective', 'adjectives', 'word', 4022],
  ['deep', 'adjective', 'adjectives', 'word', 4023],
  ['shallow', 'adjective', 'adjectives', 'word', 4024],
  ['steep', 'adjective', 'adjectives', 'word', 4025],
  ['flat', 'adjective', 'adjectives', 'word', 4026],
  ['dry', 'adjective', 'adjectives', 'word', 4027],
  ['enough', 'adjective', 'adjectives', 'word', 4028],
  ['more', 'adjective', 'adjectives', 'word', 4029],
  ['less', 'adjective', 'adjectives', 'word', 4030],
  ['same', 'adjective', 'adjectives', 'word', 4031],
  ['different', 'adjective', 'adjectives', 'word', 4032],
  ['ready', 'adjective', 'adjectives', 'word', 4033],
  ['open', 'adjective', 'adjectives', 'word', 4034],
  ['closed', 'adjective', 'adjectives', 'word', 4035],
  ['free', 'adjective', 'adjectives', 'word', 4036],
  ['busy', 'adjective', 'adjectives', 'word', 4037],
  ['full', 'adjective', 'adjectives', 'word', 4038],
  ['empty', 'adjective', 'adjectives', 'word', 4039],
  ['lost', 'adjective', 'adjectives', 'word', 4040],
  ['happy', 'adjective', 'adjectives', 'word', 4041],
  ['sad', 'adjective', 'adjectives', 'word', 4042],
  ['afraid', 'adjective', 'adjectives', 'word', 4043],
  ['strong', 'adjective', 'adjectives', 'word', 4044],
  ['weak', 'adjective', 'adjectives', 'word', 4045],

  // ═══════════════════════════════════════════════════════════════════════
  // COLORS  rank 4100–4120
  // ═══════════════════════════════════════════════════════════════════════
  ['white', 'adjective', 'colors', 'word', 4100],
  ['black', 'adjective', 'colors', 'word', 4101],
  ['red', 'adjective', 'colors', 'word', 4102],
  ['green', 'adjective', 'colors', 'word', 4103],
  ['blue', 'adjective', 'colors', 'word', 4104],
  ['yellow', 'adjective', 'colors', 'word', 4105],
  ['brown', 'adjective', 'colors', 'word', 4106],
  ['grey', 'adjective', 'colors', 'word', 4107],
  ['orange', 'adjective', 'colors', 'word', 4108],
  ['pink', 'adjective', 'colors', 'word', 4109],
  ['purple', 'adjective', 'colors', 'word', 4110],

  // ═══════════════════════════════════════════════════════════════════════
  // VERBS  rank 4200–4350
  // ═══════════════════════════════════════════════════════════════════════
  ['go', 'verb', 'verbs', 'word', 4200],
  ['come', 'verb', 'verbs', 'word', 4201],
  ['eat', 'verb', 'verbs', 'word', 4202],
  ['drink', 'verb', 'verbs', 'word', 4203],
  ['sleep', 'verb', 'verbs', 'word', 4204],
  ['wake up', 'verb', 'verbs', 'phrase', 4205],
  ['sit', 'verb', 'verbs', 'word', 4206],
  ['stand', 'verb', 'verbs', 'word', 4207],
  ['walk', 'verb', 'verbs', 'word', 4208],
  ['run', 'verb', 'verbs', 'word', 4209],
  ['stop', 'verb', 'verbs', 'word', 4210],
  ['wait', 'verb', 'verbs', 'word', 4211],
  ['open', 'verb', 'verbs', 'word', 4212],
  ['close', 'verb', 'verbs', 'word', 4213],
  ['give', 'verb', 'verbs', 'word', 4214],
  ['take', 'verb', 'verbs', 'word', 4215],
  ['buy', 'verb', 'verbs', 'word', 4216],
  ['sell', 'verb', 'verbs', 'word', 4217],
  ['cook', 'verb', 'verbs', 'word', 4218],
  ['wash', 'verb', 'verbs', 'word', 4219],
  ['carry', 'verb', 'verbs', 'word', 4220],
  ['lift', 'verb', 'verbs', 'word', 4221],
  ['push', 'verb', 'verbs', 'word', 4222],
  ['pull', 'verb', 'verbs', 'word', 4223],
  ['throw', 'verb', 'verbs', 'word', 4224],
  ['catch', 'verb', 'verbs', 'word', 4225],
  ['climb', 'verb', 'verbs', 'word', 4226],
  ['descend', 'verb', 'verbs', 'word', 4227],
  ['cross', 'verb', 'verbs', 'word', 4228],
  ['enter', 'verb', 'verbs', 'word', 4229],
  ['leave', 'verb', 'verbs', 'word', 4230],
  ['arrive', 'verb', 'verbs', 'word', 4231],
  ['return', 'verb', 'verbs', 'word', 4232],
  ['find', 'verb', 'verbs', 'word', 4233],
  ['lose', 'verb', 'verbs', 'word', 4234],
  ['look', 'verb', 'verbs', 'word', 4235],
  ['listen', 'verb', 'verbs', 'word', 4236],
  ['speak', 'verb', 'verbs', 'word', 4237],
  ['ask', 'verb', 'verbs', 'word', 4238],
  ['answer', 'verb', 'verbs', 'word', 4239],
  ['read', 'verb', 'verbs', 'word', 4240],
  ['write', 'verb', 'verbs', 'word', 4241],
  ['learn', 'verb', 'verbs', 'word', 4242],
  ['teach', 'verb', 'verbs', 'word', 4243],
  ['help', 'verb', 'verbs', 'word', 4244],
  ['call', 'verb', 'verbs', 'word', 4245],
  ['send', 'verb', 'verbs', 'word', 4246],
  ['pay', 'verb', 'verbs', 'word', 4247],
  ['share', 'verb', 'verbs', 'word', 4248],
  ['rest', 'verb', 'verbs', 'word', 4249],
  ['pray', 'verb', 'verbs', 'word', 4250],
  ['sing', 'verb', 'verbs', 'word', 4251],
  ['play', 'verb', 'verbs', 'word', 4252],
  ['work', 'verb', 'verbs', 'word', 4253],
  ['build', 'verb', 'verbs', 'word', 4254],
  ['fix', 'verb', 'verbs', 'word', 4255],

  // ═══════════════════════════════════════════════════════════════════════
  // HOUSEHOLD & DAILY LIFE  rank 4350–4450
  // ═══════════════════════════════════════════════════════════════════════
  ['house', 'noun', 'household', 'word', 4350],
  ['home', 'noun', 'household', 'word', 4351],
  ['kitchen', 'noun', 'household', 'word', 4352],
  ['fire', 'noun', 'household', 'word', 4353],
  ['stove', 'noun', 'household', 'word', 4354],
  ['pot', 'noun', 'household', 'word', 4355],
  ['pan', 'noun', 'household', 'word', 4356],
  ['bowl', 'noun', 'household', 'word', 4357],
  ['knife', 'noun', 'household', 'word', 4358],
  ['candle', 'noun', 'household', 'word', 4359],
  ['lamp', 'noun', 'household', 'word', 4360],
  ['soap', 'noun', 'household', 'word', 4361],
  ['cloth', 'noun', 'household', 'word', 4362],
  ['rope', 'noun', 'household', 'word', 4363],
  ['bag', 'noun', 'household', 'word', 4364],
  ['box', 'noun', 'household', 'word', 4365],
  ['chair', 'noun', 'household', 'word', 4366],
  ['table', 'noun', 'household', 'word', 4367],
  ['carpet', 'noun', 'household', 'word', 4368],
  ['cushion', 'noun', 'household', 'word', 4369],
  ['wood', 'noun', 'household', 'word', 4370],
  ['roof', 'noun', 'household', 'word', 4371],
  ['wall', 'noun', 'household', 'word', 4372],
  ['floor', 'noun', 'household', 'word', 4373],
  ['stairs', 'noun', 'household', 'word', 4374],

  // ═══════════════════════════════════════════════════════════════════════
  // CLOTHING  rank 4450–4510
  // ═══════════════════════════════════════════════════════════════════════
  ['clothes', 'noun', 'clothing', 'word', 4450],
  ['shirt', 'noun', 'clothing', 'word', 4451],
  ['trousers', 'noun', 'clothing', 'word', 4452],
  ['coat', 'noun', 'clothing', 'word', 4453],
  ['shoes', 'noun', 'clothing', 'word', 4454],
  ['sandals', 'noun', 'clothing', 'word', 4455],
  ['scarf', 'noun', 'clothing', 'word', 4456],
  ['shawl', 'noun', 'clothing', 'word', 4457],
  ['cap', 'noun', 'clothing', 'word', 4458],
  ['woolen cap', 'phrase', 'clothing', 'phrase', 4459],
  ['traditional hat', 'phrase', 'clothing', 'phrase', 4460],
  ['gloves', 'noun', 'clothing', 'word', 4461],
  ['socks', 'noun', 'clothing', 'word', 4462],

  // ═══════════════════════════════════════════════════════════════════════
  // AGRICULTURE & LOCAL ECONOMY  rank 4510–4600
  // ═══════════════════════════════════════════════════════════════════════
  ['farm', 'noun', 'agriculture', 'word', 4510],
  ['harvest', 'noun', 'agriculture', 'word', 4511],
  ['wheat', 'noun', 'agriculture', 'word', 4512],
  ['corn', 'noun', 'agriculture', 'word', 4513],
  ['barley', 'noun', 'agriculture', 'word', 4514],
  ['seed', 'noun', 'agriculture', 'word', 4515],
  ['irrigation', 'noun', 'agriculture', 'word', 4516],
  ['plough', 'noun', 'agriculture', 'word', 4517],
  ['shepherd', 'noun', 'agriculture', 'word', 4518],
  ['flock', 'noun', 'agriculture', 'word', 4519],
  ['wool', 'noun', 'agriculture', 'word', 4520],
  ['milk yield', 'phrase', 'agriculture', 'phrase', 4521],
  ['summer pasture', 'phrase', 'agriculture', 'phrase', 4522],
  ['winter village', 'phrase', 'agriculture', 'phrase', 4523],
  ['trader', 'noun', 'agriculture', 'word', 4524],
  ['handcraft', 'noun', 'agriculture', 'word', 4525],
  ['weaving', 'noun', 'agriculture', 'word', 4526],
  ['embroidery', 'noun', 'agriculture', 'word', 4527],
  ['gemstone', 'noun', 'agriculture', 'word', 4528],

  // ═══════════════════════════════════════════════════════════════════════
  // QUESTION WORDS & CONNECTORS  rank 4600–4650
  // ═══════════════════════════════════════════════════════════════════════
  ['what', 'pronoun', 'questions', 'word', 4600],
  ['where', 'adverb', 'questions', 'word', 4601],
  ['who', 'pronoun', 'questions', 'word', 4602],
  ['when', 'adverb', 'questions', 'word', 4603],
  ['why', 'adverb', 'questions', 'word', 4604],
  ['how', 'adverb', 'questions', 'word', 4605],
  ['which', 'pronoun', 'questions', 'word', 4606],
  ['how much', 'phrase', 'questions', 'phrase', 4607],
  ['how many', 'phrase', 'questions', 'phrase', 4608],
  ['how far', 'phrase', 'questions', 'phrase', 4609],
  ['how long', 'phrase', 'questions', 'phrase', 4610],
  ['because', 'conjunction', 'questions', 'word', 4611],
  ['but', 'conjunction', 'questions', 'word', 4612],
  ['and', 'conjunction', 'questions', 'word', 4613],
  ['or', 'conjunction', 'questions', 'word', 4614],
  ['if', 'conjunction', 'questions', 'word', 4615],
  ['i', 'pronoun', 'questions', 'word', 4616],
  ['you', 'pronoun', 'questions', 'word', 4617],
  ['he', 'pronoun', 'questions', 'word', 4618],
  ['she', 'pronoun', 'questions', 'word', 4619],
  ['we', 'pronoun', 'questions', 'word', 4620],
  ['they', 'pronoun', 'questions', 'word', 4621],
  ['this', 'pronoun', 'questions', 'word', 4622],
  ['that', 'pronoun', 'questions', 'word', 4623],

];

// ─── Build and upload ─────────────────────────────────────────────────────────

async function main() {
  // Fetch existing IDs
  const PAGE = 1000;
  let existingIds = new Set();
  let from = 0;
  while (true) {
    const { data, error } = await supabase.from('lexicon_entries').select('id').range(from, from + PAGE - 1);
    if (error) { console.error('fetch error:', error.message); process.exit(1); }
    data.forEach(r => existingIds.add(r.id));
    if (data.length < PAGE) break;
    from += PAGE;
  }
  console.log(`Existing entries in DB: ${existingIds.size}`);

  const entries = [];
  const seen    = new Set();

  for (const [en, pos, category, type, rank] of RAW) {
    const id = slug(en);
    if (existingIds.has(id) || seen.has(id)) continue;
    seen.add(id);
    entries.push({ id, type, pos, category, canonical_en: en.toLowerCase(), frequency_rank: rank });
  }

  console.log(`New entries to add: ${entries.length}`);

  // Batch insert 100 at a time
  let inserted = 0;
  for (let i = 0; i < entries.length; i += 100) {
    const batch = entries.slice(i, i + 100);
    const { error } = await supabase.from('lexicon_entries').upsert(batch, { onConflict: 'id' });
    if (error) { console.error(`Batch ${i} error:`, error.message); process.exit(1); }
    inserted += batch.length;
    process.stdout.write(`\r  Inserted ${inserted}/${entries.length}...`);
  }

  console.log(`\n\nDone! Added ${entries.length} new entries.`);
  console.log(`Total DB entries now: ~${existingIds.size + entries.length}`);
  console.log('Categories: greetings, politeness, directions, accommodation, food,');
  console.log('            transport, shopping, emergency, numbers, time, weather,');
  console.log('            nature, body, family, culture, trekking, places,');
  console.log('            adjectives, colors, verbs, household, clothing, agriculture');
}

main().catch(console.error);
