// Seeds the lexicon with common English words/phrases that need BSK translations.
// These are added as UNVERIFIED (English only) — the community fills in the BSK.

const fs   = require('fs');
const path = require('path');

const LEXICON_FILE = path.join(__dirname, '../data/lexicon.json');
const lex = JSON.parse(fs.readFileSync(LEXICON_FILE, 'utf8'));

const existingIds = new Set(lex.entries.map(e => e.id));

function id(en) {
  return en.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}

function pending(en, pos, category, type = 'word') {
  const slug = id(en);
  if (existingIds.has(slug)) return null; // skip if already in lexicon
  existingIds.add(slug);
  return {
    id: slug,
    type,
    pos,
    category,
    canonical_en: en.toLowerCase(),
    translations: {
      en: { text: en, verified: true, source: 'baseline' },
    },
    pending_contributions: [],
    updated_at: new Date().toISOString().slice(0, 10),
  };
}

const WORDS = [
  // ── Numbers ──────────────────────────────────────────────────────────────
  ['six',         'numeral', 'numbers'],
  ['seven',       'numeral', 'numbers'],
  ['eight',       'numeral', 'numbers'],
  ['nine',        'numeral', 'numbers'],
  ['ten',         'numeral', 'numbers'],
  ['eleven',      'numeral', 'numbers'],
  ['twelve',      'numeral', 'numbers'],
  ['thirteen',    'numeral', 'numbers'],
  ['fourteen',    'numeral', 'numbers'],
  ['fifteen',     'numeral', 'numbers'],
  ['sixteen',     'numeral', 'numbers'],
  ['seventeen',   'numeral', 'numbers'],
  ['eighteen',    'numeral', 'numbers'],
  ['nineteen',    'numeral', 'numbers'],
  ['twenty',      'numeral', 'numbers'],
  ['thirty',      'numeral', 'numbers'],
  ['forty',       'numeral', 'numbers'],
  ['fifty',       'numeral', 'numbers'],
  ['sixty',       'numeral', 'numbers'],
  ['seventy',     'numeral', 'numbers'],
  ['eighty',      'numeral', 'numbers'],
  ['ninety',      'numeral', 'numbers'],
  ['hundred',     'numeral', 'numbers'],
  ['thousand',    'numeral', 'numbers'],
  ['million',     'numeral', 'numbers'],
  ['first',       'adjective','numbers'],
  ['second',      'adjective','numbers'],
  ['third',       'adjective','numbers'],
  ['fourth',      'adjective','numbers'],
  ['fifth',       'adjective','numbers'],
  ['last',        'adjective','numbers'],
  ['half',        'noun',    'numbers'],
  ['zero',        'numeral', 'numbers'],

  // ── Time ─────────────────────────────────────────────────────────────────
  ['second (time)', 'noun', 'time'],
  ['minute',      'noun',   'time'],
  ['hour',        'noun',   'time'],
  ['afternoon',   'noun',   'time'],
  ['midnight',    'noun',   'time'],
  ['sunrise',     'noun',   'time'],
  ['sunset',      'noun',   'time'],
  ['season',      'noun',   'time'],
  ['spring',      'noun',   'time'],
  ['summer',      'noun',   'time'],
  ['autumn',      'noun',   'time'],
  ['winter',      'noun',   'time'],
  ['always',      'adverb', 'time'],
  ['never',       'adverb', 'time'],
  ['sometimes',   'adverb', 'time'],
  ['often',       'adverb', 'time'],
  ['soon',        'adverb', 'time'],
  ['early',       'adverb', 'time'],
  ['late',        'adverb', 'time'],
  ['before',      'adverb', 'time'],
  ['after',       'adverb', 'time'],
  ['since',       'preposition','time'],

  // ── Family & People ───────────────────────────────────────────────────────
  ['grandfather', 'noun',   'family'],
  ['grandmother', 'noun',   'family'],
  ['uncle',       'noun',   'family'],
  ['aunt',        'noun',   'family'],
  ['cousin',      'noun',   'family'],
  ['nephew',      'noun',   'family'],
  ['niece',       'noun',   'family'],
  ['baby',        'noun',   'family'],
  ['boy',         'noun',   'family'],
  ['girl',        'noun',   'family'],
  ['adult',       'noun',   'family'],
  ['elder',       'noun',   'family'],
  ['neighbour',   'noun',   'family'],
  ['guest',       'noun',   'family'],
  ['stranger',    'noun',   'family'],
  ['farmer',      'noun',   'family'],
  ['teacher',     'noun',   'family'],
  ['student',     'noun',   'family'],
  ['doctor',      'noun',   'family'],
  ['driver',      'noun',   'family'],
  ['soldier',     'noun',   'family'],
  ['leader',      'noun',   'family'],
  ['king',        'noun',   'family'],
  ['people',      'noun',   'family'],

  // ── Body ─────────────────────────────────────────────────────────────────
  ['hair',        'noun',   'body'],
  ['face',        'noun',   'body'],
  ['forehead',    'noun',   'body'],
  ['cheek',       'noun',   'body'],
  ['chin',        'noun',   'body'],
  ['tongue',      'noun',   'body'],
  ['lip',         'noun',   'body'],
  ['neck',        'noun',   'body'],
  ['shoulder',    'noun',   'body'],
  ['elbow',       'noun',   'body'],
  ['wrist',       'noun',   'body'],
  ['thumb',       'noun',   'body'],
  ['nail',        'noun',   'body'],
  ['chest',       'noun',   'body'],
  ['stomach',     'noun',   'body'],
  ['knee',        'noun',   'body'],
  ['ankle',       'noun',   'body'],
  ['toe',         'noun',   'body'],
  ['skin',        'noun',   'body'],
  ['bone',        'noun',   'body'],
  ['blood',       'noun',   'body'],
  ['brain',       'noun',   'body'],
  ['lung',        'noun',   'body'],

  // ── Colors ───────────────────────────────────────────────────────────────
  ['yellow',      'adjective','colors'],
  ['blue',        'adjective','colors'],
  ['green',       'adjective','colors'],
  ['orange',      'adjective','colors'],
  ['pink',        'adjective','colors'],
  ['purple',      'adjective','colors'],
  ['brown',       'adjective','colors'],
  ['grey',        'adjective','colors'],
  ['golden',      'adjective','colors'],
  ['silver',      'adjective','colors'],
  ['dark',        'adjective','colors'],
  ['light',       'adjective','colors'],

  // ── Nature ───────────────────────────────────────────────────────────────
  ['cloud',       'noun',   'nature'],
  ['thunder',     'noun',   'nature'],
  ['lightning',   'noun',   'nature'],
  ['flood',       'noun',   'nature'],
  ['earthquake',  'noun',   'nature'],
  ['lake',        'noun',   'nature'],
  ['sea',         'noun',   'nature'],
  ['valley',      'noun',   'nature'],
  ['glacier',     'noun',   'nature'],
  ['forest',      'noun',   'nature'],
  ['field',       'noun',   'nature'],
  ['desert',      'noun',   'nature'],
  ['soil',        'noun',   'nature'],
  ['dust',        'noun',   'nature'],
  ['fog',         'noun',   'nature'],
  ['shadow',      'noun',   'nature'],
  ['light',       'noun',   'nature'],
  ['darkness',    'noun',   'nature'],

  // ── Animals ───────────────────────────────────────────────────────────────
  ['lion',        'noun',   'animals'],
  ['leopard',     'noun',   'animals'],
  ['bear',        'noun',   'animals'],
  ['wolf',        'noun',   'animals'],
  ['fox',         'noun',   'animals'],
  ['rabbit',      'noun',   'animals'],
  ['deer',        'noun',   'animals'],
  ['eagle',       'noun',   'animals'],
  ['crow',        'noun',   'animals'],
  ['sparrow',     'noun',   'animals'],
  ['butterfly',   'noun',   'animals'],
  ['bee',         'noun',   'animals'],
  ['ant',         'noun',   'animals'],
  ['mosquito',    'noun',   'animals'],
  ['horse',       'noun',   'animals'],
  ['donkey',      'noun',   'animals'],
  ['camel',       'noun',   'animals'],
  ['cow',         'noun',   'animals'],
  ['buffalo',     'noun',   'animals'],
  ['yak',         'noun',   'animals'],
  ['chicken',     'noun',   'animals'],
  ['duck',        'noun',   'animals'],
  ['cat',         'noun',   'animals'],

  // ── Food & Drink ─────────────────────────────────────────────────────────
  ['water',       'noun',   'food'],
  ['coffee',      'noun',   'food'],
  ['juice',       'noun',   'food'],
  ['soup',        'noun',   'food'],
  ['curry',       'noun',   'food'],
  ['rice',        'noun',   'food'],
  ['wheat',       'noun',   'food'],
  ['corn',        'noun',   'food'],
  ['potato',      'noun',   'food'],
  ['onion',       'noun',   'food'],
  ['garlic',      'noun',   'food'],
  ['tomato',      'noun',   'food'],
  ['apple',       'noun',   'food'],
  ['pear',        'noun',   'food'],
  ['grape',       'noun',   'food'],
  ['mango',       'noun',   'food'],
  ['apricot',     'noun',   'food'],
  ['walnut',      'noun',   'food'],
  ['almond',      'noun',   'food'],
  ['spice',       'noun',   'food'],
  ['sweet',       'adjective','food'],
  ['sour',        'adjective','food'],
  ['bitter',      'adjective','food'],
  ['spicy',       'adjective','food'],
  ['fresh',       'adjective','food'],
  ['cooked',      'adjective','food'],
  ['raw',         'adjective','food'],
  ['boiled',      'adjective','food'],

  // ── House & Objects ───────────────────────────────────────────────────────
  ['room',        'noun',   'home'],
  ['kitchen',     'noun',   'home'],
  ['roof',        'noun',   'home'],
  ['wall',        'noun',   'home'],
  ['floor',       'noun',   'home'],
  ['ceiling',     'noun',   'home'],
  ['stair',       'noun',   'home'],
  ['gate',        'noun',   'home'],
  ['key',         'noun',   'home'],
  ['lock',        'noun',   'home'],
  ['lamp',        'noun',   'home'],
  ['fire',        'noun',   'home'],
  ['smoke',       'noun',   'home'],
  ['blanket',     'noun',   'home'],
  ['pillow',      'noun',   'home'],
  ['pot',         'noun',   'home'],
  ['cup',         'noun',   'home'],
  ['plate',       'noun',   'home'],
  ['spoon',       'noun',   'home'],
  ['knife',       'noun',   'home'],
  ['bag',         'noun',   'home'],
  ['rope',        'noun',   'home'],
  ['wood',        'noun',   'home'],
  ['cloth',       'noun',   'home'],
  ['clothes',     'noun',   'home'],
  ['shirt',       'noun',   'home'],
  ['trousers',    'noun',   'home'],
  ['shoes',       'noun',   'home'],
  ['hat',         'noun',   'home'],

  // ── Travel & Places ───────────────────────────────────────────────────────
  ['airport',     'noun',   'travel'],
  ['station',     'noun',   'travel'],
  ['bridge',      'noun',   'travel'],
  ['border',      'noun',   'travel'],
  ['passport',    'noun',   'travel'],
  ['ticket',      'noun',   'travel'],
  ['luggage',     'noun',   'travel'],
  ['taxi',        'noun',   'travel'],
  ['bus',         'noun',   'travel'],
  ['truck',       'noun',   'travel'],
  ['boat',        'noun',   'travel'],
  ['north',       'noun',   'travel'],
  ['south',       'noun',   'travel'],
  ['east',        'noun',   'travel'],
  ['west',        'noun',   'travel'],
  ['map',         'noun',   'travel'],
  ['distance',    'noun',   'travel'],
  ['hour (travel)','noun',  'travel'],
  ['kilometre',   'noun',   'travel'],
  ['uphill',      'adverb', 'travel'],
  ['downhill',    'adverb', 'travel'],
  ['path',        'noun',   'travel'],
  ['pass (mountain)','noun','travel'],

  // ── Health ────────────────────────────────────────────────────────────────
  ['pain',        'noun',   'health'],
  ['fever',       'noun',   'health'],
  ['cough',       'noun',   'health'],
  ['cold (illness)','noun', 'health'],
  ['headache',    'noun',   'health'],
  ['stomachache', 'noun',   'health'],
  ['wound',       'noun',   'health'],
  ['medicine',    'noun',   'health'],
  ['tablet',      'noun',   'health'],
  ['injection',   'noun',   'health'],
  ['bandage',     'noun',   'health'],
  ['rest',        'noun',   'health'],
  ['pregnant',    'adjective','health'],
  ['healthy',     'adjective','health'],
  ['weak',        'adjective','health'],
  ['strong',      'adjective','health'],
  ['blind',       'adjective','health'],
  ['deaf',        'adjective','health'],

  // ── Verbs ─────────────────────────────────────────────────────────────────
  ['run',         'verb',   'verbs'],
  ['walk',        'verb',   'verbs'],
  ['stand',       'verb',   'verbs'],
  ['sit',         'verb',   'verbs'],
  ['lie down',    'verb',   'verbs'],
  ['wake up',     'verb',   'verbs'],
  ['wash',        'verb',   'verbs'],
  ['clean',       'verb',   'verbs'],
  ['cook',        'verb',   'verbs'],
  ['carry',       'verb',   'verbs'],
  ['lift',        'verb',   'verbs'],
  ['throw',       'verb',   'verbs'],
  ['catch',       'verb',   'verbs'],
  ['cut',         'verb',   'verbs'],
  ['break',       'verb',   'verbs'],
  ['fix',         'verb',   'verbs'],
  ['build',       'verb',   'verbs'],
  ['plant',       'verb',   'verbs'],
  ['hunt',        'verb',   'verbs'],
  ['fish',        'verb',   'verbs'],
  ['climb',       'verb',   'verbs'],
  ['fall',        'verb',   'verbs'],
  ['swim',        'verb',   'verbs'],
  ['sing',        'verb',   'verbs'],
  ['dance',       'verb',   'verbs'],
  ['laugh',       'verb',   'verbs'],
  ['cry',         'verb',   'verbs'],
  ['pray',        'verb',   'verbs'],
  ['wait',        'verb',   'verbs'],
  ['search',      'verb',   'verbs'],
  ['find',        'verb',   'verbs'],
  ['lose',        'verb',   'verbs'],
  ['forget',      'verb',   'verbs'],
  ['remember',    'verb',   'verbs'],
  ['believe',     'verb',   'verbs'],
  ['feel',        'verb',   'verbs'],
  ['touch',       'verb',   'verbs'],
  ['smell',       'verb',   'verbs'],
  ['taste',       'verb',   'verbs'],
  ['send',        'verb',   'verbs'],
  ['receive',     'verb',   'verbs'],
  ['return',      'verb',   'verbs'],
  ['leave',       'verb',   'verbs'],
  ['arrive',      'verb',   'verbs'],
  ['meet',        'verb',   'verbs'],
  ['follow',      'verb',   'verbs'],
  ['show',        'verb',   'verbs'],
  ['hide',        'verb',   'verbs'],
  ['change',      'verb',   'verbs'],
  ['start',       'verb',   'verbs'],
  ['stop',        'verb',   'verbs'],
  ['finish',      'verb',   'verbs'],
  ['try',         'verb',   'verbs'],
  ['agree',       'verb',   'verbs'],
  ['refuse',      'verb',   'verbs'],
  ['fight',       'verb',   'verbs'],
  ['win',         'verb',   'verbs'],
  ['lose (competition)', 'verb', 'verbs'],
  ['pay',         'verb',   'verbs'],
  ['borrow',      'verb',   'verbs'],
  ['lend',        'verb',   'verbs'],
  ['steal',       'verb',   'verbs'],
  ['protect',     'verb',   'verbs'],

  // ── Adjectives ────────────────────────────────────────────────────────────
  ['tall',        'adjective','adjectives'],
  ['short',       'adjective','adjectives'],
  ['thin',        'adjective','adjectives'],
  ['fat',         'adjective','adjectives'],
  ['wide',        'adjective','adjectives'],
  ['narrow',      'adjective','adjectives'],
  ['deep',        'adjective','adjectives'],
  ['shallow',     'adjective','adjectives'],
  ['heavy',       'adjective','adjectives'],
  ['light (weight)','adjective','adjectives'],
  ['wet',         'adjective','adjectives'],
  ['dry',         'adjective','adjectives'],
  ['clean',       'adjective','adjectives'],
  ['dirty',       'adjective','adjectives'],
  ['full',        'adjective','adjectives'],
  ['empty',       'adjective','adjectives'],
  ['open',        'adjective','adjectives'],
  ['closed',      'adjective','adjectives'],
  ['loud',        'adjective','adjectives'],
  ['quiet',       'adjective','adjectives'],
  ['safe',        'adjective','adjectives'],
  ['dangerous',   'adjective','adjectives'],
  ['true',        'adjective','adjectives'],
  ['false',       'adjective','adjectives'],
  ['possible',    'adjective','adjectives'],
  ['impossible',  'adjective','adjectives'],
  ['important',   'adjective','adjectives'],
  ['rich',        'adjective','adjectives'],
  ['poor',        'adjective','adjectives'],
  ['lucky',       'adjective','adjectives'],
  ['tired',       'adjective','adjectives'],
  ['afraid',      'adjective','adjectives'],
  ['angry',       'adjective','adjectives'],
  ['surprised',   'adjective','adjectives'],
  ['bored',       'adjective','adjectives'],
  ['busy',        'adjective','adjectives'],
  ['free',        'adjective','adjectives'],
  ['alive',       'adjective','adjectives'],
  ['dead',        'adjective','adjectives'],

  // ── Common phrases ────────────────────────────────────────────────────────
  ['how do you say X in Burushaski', 'phrase', 'phrases', 'phrase'],
  ['I want to learn Burushaski',     'phrase', 'phrases', 'phrase'],
  ['can you teach me',               'phrase', 'phrases', 'phrase'],
  ['what does this word mean',       'phrase', 'phrases', 'phrase'],
  ['I am a tourist',                 'phrase', 'phrases', 'phrase'],
  ['I am visiting from',             'phrase', 'phrases', 'phrase'],
  ['I am lost',                      'phrase', 'phrases', 'phrase'],
  ['I need help',                    'phrase', 'phrases', 'phrase'],
  ['please wait',                    'phrase', 'phrases', 'phrase'],
  ['please come',                    'phrase', 'phrases', 'phrase'],
  ['please go',                      'phrase', 'phrases', 'phrase'],
  ['please give me',                 'phrase', 'phrases', 'phrase'],
  ['please show me',                 'phrase', 'phrases', 'phrase'],
  ['how long does it take',          'phrase', 'phrases', 'phrase'],
  ['how far is it',                  'phrase', 'phrases', 'phrase'],
  ['take me to',                     'phrase', 'phrases', 'phrase'],
  ['I want to go to',                'phrase', 'phrases', 'phrase'],
  ['I arrived today',                'phrase', 'phrases', 'phrase'],
  ['I am leaving tomorrow',          'phrase', 'phrases', 'phrase'],
  ['I will stay for X days',         'phrase', 'phrases', 'phrase'],
  ['this is very beautiful',         'phrase', 'phrases', 'phrase'],
  ['this place is amazing',          'phrase', 'phrases', 'phrase'],
  ['the weather is cold',            'phrase', 'phrases', 'phrase'],
  ['the weather is hot',             'phrase', 'phrases', 'phrase'],
  ['it is raining',                  'phrase', 'phrases', 'phrase'],
  ['it is snowing',                  'phrase', 'phrases', 'phrase'],
  ['I am allergic to',               'phrase', 'phrases', 'phrase'],
  ['I have a headache',              'phrase', 'phrases', 'phrase'],
  ['I have a fever',                 'phrase', 'phrases', 'phrase'],
  ['I need a doctor',                'phrase', 'phrases', 'phrase'],
  ['where is the nearest hospital',  'phrase', 'phrases', 'phrase'],
  ['can I take a photo',             'phrase', 'phrases', 'phrase'],
  ['you are very kind',              'phrase', 'phrases', 'phrase'],
  ['I like this place',              'phrase', 'phrases', 'phrase'],
  ['can I sit here',                 'phrase', 'phrases', 'phrase'],
  ['what is the price',              'phrase', 'phrases', 'phrase'],
  ['do you have',                    'phrase', 'phrases', 'phrase'],
  ['how many do you have',           'phrase', 'phrases', 'phrase'],
  ['I will come back',               'phrase', 'phrases', 'phrase'],
  ['let us go',                      'phrase', 'phrases', 'phrase'],
  ['follow me',                      'phrase', 'phrases', 'phrase'],
  ['be careful',                     'phrase', 'phrases', 'phrase'],
  ['do not worry',                   'phrase', 'phrases', 'phrase'],
  ['everything is fine',             'phrase', 'phrases', 'phrase'],
  ['God willing',                    'phrase', 'phrases', 'phrase'],
  ['congratulations',                'phrase', 'phrases', 'phrase'],
  ['happy birthday',                 'phrase', 'phrases', 'phrase'],
  ['get well soon',                  'phrase', 'phrases', 'phrase'],
  ['I am praying for you',           'phrase', 'phrases', 'phrase'],
  ['good luck',                      'phrase', 'phrases', 'phrase'],
  ['welcome',                        'phrase', 'phrases', 'phrase'],
  ['safe travels',                   'phrase', 'phrases', 'phrase'],
];

let added = 0;
for (const args of WORDS) {
  const entry = pending(...args);
  if (entry) { lex.entries.push(entry); added++; }
}

lex.updated_at    = new Date().toISOString().slice(0, 10);
lex.total_entries = lex.entries.length;
lex.verified_bsk  = lex.entries.filter(e => e.translations?.bsk?.verified).length;
lex.pending_bsk   = lex.entries.filter(e => !e.translations?.bsk).length;

fs.writeFileSync(LEXICON_FILE, JSON.stringify(lex, null, 2), 'utf8');

console.log(`Added  : ${added} new pending entries`);
console.log(`Total  : ${lex.total_entries} entries`);
console.log(`Verified BSK : ${lex.verified_bsk}`);
console.log(`Pending BSK  : ${lex.pending_bsk}`);
