// Frequency-ordered word seed — entries appear in the contribute queue
// from most common (rank 1) to least common (rank ~10000).
// Sources: Oxford 5000, BNC frequency lists, COCA corpus, Oxford 3000.
// Format: [english, pos, category, type, frequency_rank]

const fs   = require('fs');
const path = require('path');
const LEXICON_FILE = path.join(__dirname, '../data/lexicon.json');
const lex  = JSON.parse(fs.readFileSync(LEXICON_FILE, 'utf8'));
const existingIds = new Set(lex.entries.map(e => e.id));

function slug(en) {
  return en.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '');
}
function add(en, pos, category, type = 'word', rank = 9999) {
  const id = slug(en);
  if (existingIds.has(id)) return null;
  existingIds.add(id);
  return {
    id, type, pos, category,
    canonical_en: en.toLowerCase(),
    frequency_rank: rank,
    translations: { en: { text: en, verified: true, source: 'baseline' } },
    pending_contributions: [],
    updated_at: new Date().toISOString().slice(0,10),
  };
}

const WORDS = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TIER 1  rank 1–200  Core grammar & most frequent words
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ['be',           'verb',        'core',        'word',   1],
  ['have',         'verb',        'core',        'word',   2],
  ['do',           'verb',        'core',        'word',   3],
  ['say',          'verb',        'core',        'word',   4],
  ['get',          'verb',        'core',        'word',   5],
  ['make',         'verb',        'core',        'word',   6],
  ['know',         'verb',        'core',        'word',   7],
  ['think',        'verb',        'core',        'word',   8],
  ['take',         'verb',        'core',        'word',   9],
  ['see',          'verb',        'core',        'word',  10],
  ['not',          'adverb',      'core',        'word',  11],
  ['all',          'determiner',  'core',        'word',  12],
  ['also',         'adverb',      'core',        'word',  13],
  ['can',          'verb',        'core',        'word',  14],
  ['will',         'verb',        'core',        'word',  15],
  ['would',        'verb',        'core',        'word',  16],
  ['could',        'verb',        'core',        'word',  17],
  ['should',       'verb',        'core',        'word',  18],
  ['may',          'verb',        'core',        'word',  19],
  ['might',        'verb',        'core',        'word',  20],
  ['must',         'verb',        'core',        'word',  21],
  ['shall',        'verb',        'core',        'word',  22],
  ['need',         'verb',        'core',        'word',  23],
  ['want',         'verb',        'core',        'word',  24],
  ['seem',         'verb',        'core',        'word',  25],
  ['become',       'verb',        'core',        'word',  26],
  ['keep',         'verb',        'core',        'word',  27],
  ['let',          'verb',        'core',        'word',  28],
  ['begin',        'verb',        'core',        'word',  29],
  ['show',         'verb',        'core',        'word',  30],
  ['turn',         'verb',        'core',        'word',  31],
  ['move',         'verb',        'core',        'word',  32],
  ['live',         'verb',        'core',        'word',  33],
  ['happen',       'verb',        'core',        'word',  34],
  ['mean',         'verb',        'core',        'word',  35],
  ['put',          'verb',        'core',        'word',  36],
  ['try',          'verb',        'core',        'word',  37],
  ['leave',        'verb',        'core',        'word',  38],
  ['call',         'verb',        'core',        'word',  39],
  ['hold',         'verb',        'core',        'word',  40],
  ['bring',        'verb',        'core',        'word',  41],
  ['continue',     'verb',        'core',        'word',  42],
  ['set',          'verb',        'core',        'word',  43],
  ['change',       'verb',        'core',        'word',  44],
  ['lead',         'verb',        'core',        'word',  45],
  ['understand',   'verb',        'core',        'word',  46],
  ['watch',        'verb',        'core',        'word',  47],
  ['follow',       'verb',        'core',        'word',  48],
  ['create',       'verb',        'core',        'word',  49],
  ['consider',     'verb',        'core',        'word',  50],

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Most frequent nouns  (rank 51–300)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ['time',         'noun',        'core',        'word',  51],
  ['year',         'noun',        'core',        'word',  52],
  ['way',          'noun',        'core',        'word',  53],
  ['day',          'noun',        'core',        'word',  54],
  ['thing',        'noun',        'core',        'word',  55],
  ['man',          'noun',        'core',        'word',  56],
  ['world',        'noun',        'core',        'word',  57],
  ['life',         'noun',        'core',        'word',  58],
  ['hand',         'noun',        'body',        'word',  59],
  ['part',         'noun',        'core',        'word',  60],
  ['place',        'noun',        'core',        'word',  61],
  ['case',         'noun',        'core',        'word',  62],
  ['week',         'noun',        'time',        'word',  63],
  ['point',        'noun',        'core',        'word',  64],
  ['number',       'noun',        'numbers',     'word',  65],
  ['night',        'noun',        'time',        'word',  66],
  ['area',         'noun',        'core',        'word',  67],
  ['money',        'noun',        'commerce',    'word',  68],
  ['story',        'noun',        'core',        'word',  69],
  ['fact',         'noun',        'core',        'word',  70],
  ['month',        'noun',        'time',        'word',  71],
  ['lot',          'noun',        'core',        'word',  72],
  ['right',        'noun',        'core',        'word',  73],
  ['study',        'noun',        'education',   'word',  74],
  ['book',         'noun',        'education',   'word',  75],
  ['eye',          'noun',        'body',        'word',  76],
  ['job',          'noun',        'work',        'word',  77],
  ['word',         'noun',        'language',    'word',  78],
  ['business',     'noun',        'commerce',    'word',  79],
  ['side',         'noun',        'core',        'word',  80],
  ['kind',         'noun',        'core',        'word',  81],
  ['head',         'noun',        'body',        'word',  82],
  ['house',        'noun',        'home',        'word',  83],
  ['service',      'noun',        'work',        'word',  84],
  ['power',        'noun',        'core',        'word',  85],
  ['town',         'noun',        'places',      'word',  86],
  ['city',         'noun',        'places',      'word',  87],
  ['country',      'noun',        'places',      'word',  88],
  ['area',         'noun',        'places',      'word',  89],
  ['system',       'noun',        'core',        'word',  90],
  ['program',      'noun',        'education',   'word',  91],
  ['question',     'noun',        'core',        'word',  92],
  ['body',         'noun',        'body',        'word',  93],
  ['information',  'noun',        'core',        'word',  94],
  ['back',         'noun',        'body',        'word',  95],
  ['parent',       'noun',        'family',      'word',  96],
  ['face',         'noun',        'body',        'word',  97],
  ['others',       'noun',        'core',        'word',  98],
  ['level',        'noun',        'core',        'word',  99],
  ['office',       'noun',        'work',        'word', 100],
  ['door',         'noun',        'home',        'word', 101],
  ['health',       'noun',        'health',      'word', 102],
  ['person',       'noun',        'family',      'word', 103],
  ['art',          'noun',        'culture',     'word', 104],
  ['war',          'noun',        'society',     'word', 105],
  ['history',      'noun',        'culture',     'word', 106],
  ['party',        'noun',        'social',      'word', 107],
  ['result',       'noun',        'core',        'word', 108],
  ['change',       'noun',        'core',        'word', 109],
  ['morning',      'noun',        'time',        'word', 110],
  ['reason',       'noun',        'core',        'word', 111],
  ['research',     'noun',        'education',   'word', 112],
  ['girl',         'noun',        'family',      'word', 113],
  ['guy',          'noun',        'family',      'word', 114],
  ['moment',       'noun',        'time',        'word', 115],
  ['air',          'noun',        'nature',      'word', 116],
  ['teacher',      'noun',        'education',   'word', 117],
  ['force',        'noun',        'core',        'word', 118],
  ['education',    'noun',        'education',   'word', 119],
  ['never',        'adverb',      'time',        'word', 120],
  ['able',         'adjective',   'core',        'word', 121],
  ['town',         'noun',        'places',      'word', 122],
  ['usually',      'adverb',      'core',        'word', 123],
  ['early',        'adjective',   'time',        'word', 124],
  ['school',       'noun',        'education',   'word', 125],
  ['still',        'adverb',      'core',        'word', 126],
  ['group',        'noun',        'core',        'word', 127],
  ['often',        'adverb',      'time',        'word', 128],
  ['run',          'verb',        'verbs',       'word', 129],
  ['important',    'adjective',   'adjectives',  'word', 130],
  ['until',        'conjunction', 'core',        'word', 131],
  ['children',     'noun',        'family',      'word', 132],
  ['side',         'noun',        'core',        'word', 133],
  ['feet',         'noun',        'body',        'word', 134],
  ['car',          'noun',        'travel',      'word', 135],
  ['mile',         'noun',        'travel',      'word', 136],
  ['night',        'noun',        'time',        'word', 137],
  ['walk',         'verb',        'verbs',       'word', 138],
  ['white',        'adjective',   'colors',      'word', 139],
  ['sea',          'noun',        'nature',      'word', 140],
  ['began',        'verb',        'core',        'word', 141],
  ['grow',         'verb',        'verbs',       'word', 142],
  ['took',         'verb',        'core',        'word', 143],
  ['river',        'noun',        'nature',      'word', 144],
  ['four',         'numeral',     'numbers',     'word', 145],
  ['carry',        'verb',        'verbs',       'word', 146],
  ['state',        'noun',        'places',      'word', 147],
  ['once',         'adverb',      'time',        'word', 148],
  ['book',         'noun',        'education',   'word', 149],
  ['hear',         'verb',        'verbs',       'word', 150],

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TIER 2  rank 301–1500  Common everyday vocabulary
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  // Verbs
  ['speak',        'verb',        'verbs',       'word', 301],
  ['spend',        'verb',        'verbs',       'word', 302],
  ['cut',          'verb',        'verbs',       'word', 303],
  ['reach',        'verb',        'verbs',       'word', 304],
  ['kill',         'verb',        'verbs',       'word', 305],
  ['remain',       'verb',        'verbs',       'word', 306],
  ['suggest',      'verb',        'verbs',       'word', 307],
  ['raise',        'verb',        'verbs',       'word', 308],
  ['pass',         'verb',        'verbs',       'word', 309],
  ['sell',         'verb',        'verbs',       'word', 310],
  ['decide',       'verb',        'verbs',       'word', 311],
  ['break',        'verb',        'verbs',       'word', 312],
  ['choose',       'verb',        'verbs',       'word', 313],
  ['stand',        'verb',        'verbs',       'word', 314],
  ['lose',         'verb',        'verbs',       'word', 315],
  ['pay',          'verb',        'verbs',       'word', 316],
  ['meet',         'verb',        'verbs',       'word', 317],
  ['include',      'verb',        'verbs',       'word', 318],
  ['die',          'verb',        'verbs',       'word', 319],
  ['send',         'verb',        'verbs',       'word', 320],
  ['expect',       'verb',        'verbs',       'word', 321],
  ['build',        'verb',        'verbs',       'word', 322],
  ['stay',         'verb',        'verbs',       'word', 323],
  ['fall',         'verb',        'verbs',       'word', 324],
  ['save',         'verb',        'verbs',       'word', 325],
  ['offer',        'verb',        'verbs',       'word', 326],
  ['open',         'verb',        'verbs',       'word', 327],
  ['close',        'verb',        'verbs',       'word', 328],
  ['pull',         'verb',        'verbs',       'word', 329],
  ['push',         'verb',        'verbs',       'word', 330],
  ['check',        'verb',        'verbs',       'word', 331],
  ['add',          'verb',        'verbs',       'word', 332],
  ['fill',         'verb',        'verbs',       'word', 333],
  ['return',       'verb',        'verbs',       'word', 334],
  ['arrive',       'verb',        'verbs',       'word', 335],
  ['enter',        'verb',        'verbs',       'word', 336],
  ['sit',          'verb',        'verbs',       'word', 337],
  ['drop',         'verb',        'verbs',       'word', 338],
  ['act',          'verb',        'verbs',       'word', 339],
  ['allow',        'verb',        'verbs',       'word', 340],
  ['ask',          'verb',        'verbs',       'word', 341],
  ['appear',       'verb',        'verbs',       'word', 342],
  ['accept',       'verb',        'verbs',       'word', 343],
  ['help',         'verb',        'verbs',       'word', 344],
  ['love',         'verb',        'verbs',       'word', 345],
  ['share',        'verb',        'verbs',       'word', 346],
  ['need',         'verb',        'verbs',       'word', 347],
  ['play',         'verb',        'verbs',       'word', 348],
  ['move',         'verb',        'verbs',       'word', 349],
  ['use',          'verb',        'verbs',       'word', 350],

  // Adjectives
  ['new',          'adjective',   'adjectives',  'word', 351],
  ['old',          'adjective',   'adjectives',  'word', 352],
  ['great',        'adjective',   'adjectives',  'word', 353],
  ['high',         'adjective',   'adjectives',  'word', 354],
  ['little',       'adjective',   'adjectives',  'word', 355],
  ['own',          'adjective',   'adjectives',  'word', 356],
  ['right',        'adjective',   'adjectives',  'word', 357],
  ['large',        'adjective',   'adjectives',  'word', 358],
  ['next',         'adjective',   'adjectives',  'word', 359],
  ['early',        'adjective',   'adjectives',  'word', 360],
  ['young',        'adjective',   'adjectives',  'word', 361],
  ['long',         'adjective',   'adjectives',  'word', 362],
  ['different',    'adjective',   'adjectives',  'word', 363],
  ['few',          'adjective',   'adjectives',  'word', 364],
  ['real',         'adjective',   'adjectives',  'word', 365],
  ['sure',         'adjective',   'adjectives',  'word', 366],
  ['hard',         'adjective',   'adjectives',  'word', 367],
  ['last',         'adjective',   'adjectives',  'word', 368],
  ['next',         'adjective',   'adjectives',  'word', 369],
  ['same',         'adjective',   'adjectives',  'word', 370],
  ['social',       'adjective',   'adjectives',  'word', 371],
  ['national',     'adjective',   'adjectives',  'word', 372],
  ['local',        'adjective',   'adjectives',  'word', 373],
  ['public',       'adjective',   'adjectives',  'word', 374],
  ['political',    'adjective',   'adjectives',  'word', 375],
  ['economic',     'adjective',   'adjectives',  'word', 376],
  ['personal',     'adjective',   'adjectives',  'word', 377],
  ['human',        'adjective',   'adjectives',  'word', 378],
  ['natural',      'adjective',   'adjectives',  'word', 379],
  ['simple',       'adjective',   'adjectives',  'word', 380],
  ['certain',      'adjective',   'adjectives',  'word', 381],
  ['possible',     'adjective',   'adjectives',  'word', 382],
  ['ready',        'adjective',   'adjectives',  'word', 383],
  ['main',         'adjective',   'adjectives',  'word', 384],
  ['whole',        'adjective',   'adjectives',  'word', 385],
  ['low',          'adjective',   'adjectives',  'word', 386],
  ['special',      'adjective',   'adjectives',  'word', 387],
  ['clear',        'adjective',   'adjectives',  'word', 388],
  ['true',         'adjective',   'adjectives',  'word', 389],
  ['short',        'adjective',   'adjectives',  'word', 390],
  ['past',         'adjective',   'adjectives',  'word', 391],
  ['recent',       'adjective',   'adjectives',  'word', 392],
  ['available',    'adjective',   'adjectives',  'word', 393],
  ['traditional',  'adjective',   'adjectives',  'word', 394],
  ['former',       'adjective',   'adjectives',  'word', 395],
  ['various',      'adjective',   'adjectives',  'word', 396],
  ['direct',       'adjective',   'adjectives',  'word', 397],
  ['free',         'adjective',   'adjectives',  'word', 398],
  ['full',         'adjective',   'adjectives',  'word', 399],
  ['able',         'adjective',   'adjectives',  'word', 400],

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TIER 3  rank 1501–4000  Intermediate vocabulary
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  // People & relationships
  ['woman',        'noun',        'family',      'word', 401],
  ['husband',      'noun',        'family',      'word', 402],
  ['wife',         'noun',        'family',      'word', 403],
  ['baby',         'noun',        'family',      'word', 404],
  ['son',          'noun',        'family',      'word', 405],
  ['daughter',     'noun',        'family',      'word', 406],
  ['brother',      'noun',        'family',      'word', 407],
  ['sister',       'noun',        'family',      'word', 408],
  ['grandfather',  'noun',        'family',      'word', 409],
  ['grandmother',  'noun',        'family',      'word', 410],
  ['uncle',        'noun',        'family',      'word', 411],
  ['aunt',         'noun',        'family',      'word', 412],
  ['cousin',       'noun',        'family',      'word', 413],
  ['neighbour',    'noun',        'family',      'word', 414],
  ['guest',        'noun',        'social',      'word', 415],
  ['leader',       'noun',        'society',     'word', 416],
  ['elder',        'noun',        'family',      'word', 417],
  ['youth',        'noun',        'family',      'word', 418],
  ['couple',       'noun',        'family',      'word', 419],
  ['family',       'noun',        'family',      'word', 420],
  ['community',    'noun',        'society',     'word', 421],
  ['citizen',      'noun',        'society',     'word', 422],
  ['soldier',      'noun',        'society',     'word', 423],
  ['doctor',       'noun',        'health',      'word', 424],
  ['nurse',        'noun',        'health',      'word', 425],
  ['farmer',       'noun',        'work',        'word', 426],
  ['driver',       'noun',        'work',        'word', 427],
  ['worker',       'noun',        'work',        'word', 428],
  ['engineer',     'noun',        'work',        'word', 429],
  ['police',       'noun',        'society',     'word', 430],
  ['judge',        'noun',        'society',     'word', 431],
  ['king',         'noun',        'society',     'word', 432],
  ['queen',        'noun',        'society',     'word', 433],
  ['president',    'noun',        'society',     'word', 434],
  ['minister',     'noun',        'society',     'word', 435],
  ['journalist',   'noun',        'work',        'word', 436],
  ['artist',       'noun',        'culture',     'word', 437],
  ['poet',         'noun',        'culture',     'word', 438],
  ['musician',     'noun',        'culture',     'word', 439],
  ['actor',        'noun',        'culture',     'word', 440],
  ['chef',         'noun',        'work',        'word', 441],
  ['merchant',     'noun',        'commerce',    'word', 442],
  ['servant',      'noun',        'work',        'word', 443],
  ['guest',        'noun',        'social',      'word', 444],
  ['host',         'noun',        'social',      'word', 445],
  ['stranger',     'noun',        'social',      'word', 446],
  ['enemy',        'noun',        'society',     'word', 447],
  ['ally',         'noun',        'society',     'word', 448],
  ['hero',         'noun',        'culture',     'word', 449],
  ['victim',       'noun',        'health',      'word', 450],

  // Body & health (extended)
  ['hair',         'noun',        'body',        'word', 451],
  ['ear',          'noun',        'body',        'word', 452],
  ['nose',         'noun',        'body',        'word', 453],
  ['mouth',        'noun',        'body',        'word', 454],
  ['tooth',        'noun',        'body',        'word', 455],
  ['tongue',       'noun',        'body',        'word', 456],
  ['neck',         'noun',        'body',        'word', 457],
  ['shoulder',     'noun',        'body',        'word', 458],
  ['arm',          'noun',        'body',        'word', 459],
  ['elbow',        'noun',        'body',        'word', 460],
  ['wrist',        'noun',        'body',        'word', 461],
  ['finger',       'noun',        'body',        'word', 462],
  ['thumb',        'noun',        'body',        'word', 463],
  ['nail',         'noun',        'body',        'word', 464],
  ['chest',        'noun',        'body',        'word', 465],
  ['stomach',      'noun',        'body',        'word', 466],
  ['knee',         'noun',        'body',        'word', 467],
  ['ankle',        'noun',        'body',        'word', 468],
  ['toe',          'noun',        'body',        'word', 469],
  ['skin',         'noun',        'body',        'word', 470],
  ['bone',         'noun',        'body',        'word', 471],
  ['blood',        'noun',        'body',        'word', 472],
  ['brain',        'noun',        'body',        'word', 473],
  ['lung',         'noun',        'body',        'word', 474],
  ['kidney',       'noun',        'body',        'word', 475],
  ['liver',        'noun',        'body',        'word', 476],
  ['throat',       'noun',        'body',        'word', 477],
  ['lip',          'noun',        'body',        'word', 478],
  ['chin',         'noun',        'body',        'word', 479],
  ['forehead',     'noun',        'body',        'word', 480],
  ['eyebrow',      'noun',        'body',        'word', 481],
  ['eyelash',      'noun',        'body',        'word', 482],
  ['beard',        'noun',        'body',        'word', 483],
  ['moustache',    'noun',        'body',        'word', 484],
  ['cheek',        'noun',        'body',        'word', 485],
  ['muscle',       'noun',        'body',        'word', 486],
  ['nerve',        'noun',        'body',        'word', 487],
  ['vein',         'noun',        'body',        'word', 488],
  ['sweat',        'noun',        'body',        'word', 489],
  ['tear',         'noun',        'body',        'word', 490],
  ['sneeze',       'verb',        'health',      'word', 491],
  ['cough',        'verb',        'health',      'word', 492],
  ['breathe',      'verb',        'health',      'word', 493],
  ['pain',         'noun',        'health',      'word', 494],
  ['fever',        'noun',        'health',      'word', 495],
  ['headache',     'noun',        'health',      'word', 496],
  ['cold',         'noun',        'health',      'word', 497],
  ['flu',          'noun',        'health',      'word', 498],
  ['allergy',      'noun',        'health',      'word', 499],
  ['medicine',     'noun',        'health',      'word', 500],

  // Nature & environment (extended)
  ['sky',          'noun',        'nature',      'word', 501],
  ['sun',          'noun',        'nature',      'word', 502],
  ['moon',         'noun',        'nature',      'word', 503],
  ['star',         'noun',        'nature',      'word', 504],
  ['cloud',        'noun',        'nature',      'word', 505],
  ['rain',         'noun',        'nature',      'word', 506],
  ['snow',         'noun',        'nature',      'word', 507],
  ['wind',         'noun',        'nature',      'word', 508],
  ['storm',        'noun',        'nature',      'word', 509],
  ['thunder',      'noun',        'nature',      'word', 510],
  ['lightning',    'noun',        'nature',      'word', 511],
  ['ice',          'noun',        'nature',      'word', 512],
  ['frost',        'noun',        'nature',      'word', 513],
  ['fog',          'noun',        'nature',      'word', 514],
  ['hail',         'noun',        'nature',      'word', 515],
  ['flood',        'noun',        'nature',      'word', 516],
  ['earthquake',   'noun',        'nature',      'word', 517],
  ['avalanche',    'noun',        'nature',      'word', 518],
  ['mountain',     'noun',        'nature',      'word', 519],
  ['valley',       'noun',        'nature',      'word', 520],
  ['glacier',      'noun',        'nature',      'word', 521],
  ['pass',         'noun',        'nature',      'word', 522],
  ['peak',         'noun',        'nature',      'word', 523],
  ['cliff',        'noun',        'nature',      'word', 524],
  ['forest',       'noun',        'nature',      'word', 525],
  ['jungle',       'noun',        'nature',      'word', 526],
  ['desert',       'noun',        'nature',      'word', 527],
  ['field',        'noun',        'nature',      'word', 528],
  ['meadow',       'noun',        'nature',      'word', 529],
  ['lake',         'noun',        'nature',      'word', 530],
  ['stream',       'noun',        'nature',      'word', 531],
  ['waterfall',    'noun',        'nature',      'word', 532],
  ['spring',       'noun',        'nature',      'word', 533],
  ['soil',         'noun',        'nature',      'word', 534],
  ['rock',         'noun',        'nature',      'word', 535],
  ['sand',         'noun',        'nature',      'word', 536],
  ['dust',         'noun',        'nature',      'word', 537],
  ['mud',          'noun',        'nature',      'word', 538],
  ['tree',         'noun',        'nature',      'word', 539],
  ['flower',       'noun',        'nature',      'word', 540],
  ['grass',        'noun',        'nature',      'word', 541],
  ['leaf',         'noun',        'nature',      'word', 542],
  ['seed',         'noun',        'nature',      'word', 543],
  ['root',         'noun',        'nature',      'word', 544],
  ['branch',       'noun',        'nature',      'word', 545],
  ['fruit',        'noun',        'food',        'word', 546],
  ['shadow',       'noun',        'nature',      'word', 547],
  ['air',          'noun',        'nature',      'word', 548],
  ['light',        'noun',        'nature',      'word', 549],
  ['darkness',     'noun',        'nature',      'word', 550],

  // Animals (extended)
  ['animal',       'noun',        'animals',     'word', 551],
  ['bird',         'noun',        'animals',     'word', 552],
  ['fish',         'noun',        'animals',     'word', 553],
  ['dog',          'noun',        'animals',     'word', 554],
  ['cat',          'noun',        'animals',     'word', 555],
  ['horse',        'noun',        'animals',     'word', 556],
  ['cow',          'noun',        'animals',     'word', 557],
  ['sheep',        'noun',        'animals',     'word', 558],
  ['goat',         'noun',        'animals',     'word', 559],
  ['donkey',       'noun',        'animals',     'word', 560],
  ['camel',        'noun',        'animals',     'word', 561],
  ['chicken',      'noun',        'animals',     'word', 562],
  ['duck',         'noun',        'animals',     'word', 563],
  ['eagle',        'noun',        'animals',     'word', 564],
  ['crow',         'noun',        'animals',     'word', 565],
  ['sparrow',      'noun',        'animals',     'word', 566],
  ['wolf',         'noun',        'animals',     'word', 567],
  ['bear',         'noun',        'animals',     'word', 568],
  ['lion',         'noun',        'animals',     'word', 569],
  ['leopard',      'noun',        'animals',     'word', 570],
  ['fox',          'noun',        'animals',     'word', 571],
  ['rabbit',       'noun',        'animals',     'word', 572],
  ['deer',         'noun',        'animals',     'word', 573],
  ['yak',          'noun',        'animals',     'word', 574],
  ['buffalo',      'noun',        'animals',     'word', 575],
  ['elephant',     'noun',        'animals',     'word', 576],
  ['monkey',       'noun',        'animals',     'word', 577],
  ['snake',        'noun',        'animals',     'word', 578],
  ['frog',         'noun',        'animals',     'word', 579],
  ['bee',          'noun',        'animals',     'word', 580],
  ['butterfly',    'noun',        'animals',     'word', 581],
  ['ant',          'noun',        'animals',     'word', 582],
  ['mosquito',     'noun',        'animals',     'word', 583],
  ['fly',          'noun',        'animals',     'word', 584],
  ['spider',       'noun',        'animals',     'word', 585],
  ['mouse',        'noun',        'animals',     'word', 586],
  ['rat',          'noun',        'animals',     'word', 587],
  ['insect',       'noun',        'animals',     'word', 588],
  ['wing',         'noun',        'animals',     'word', 589],
  ['tail',         'noun',        'animals',     'word', 590],
  ['feather',      'noun',        'animals',     'word', 591],
  ['horn',         'noun',        'animals',     'word', 592],
  ['fur',          'noun',        'animals',     'word', 593],
  ['hoof',         'noun',        'animals',     'word', 594],
  ['nest',         'noun',        'animals',     'word', 595],
  ['egg',          'noun',        'food',        'word', 596],
  ['wool',         'noun',        'home',        'word', 597],
  ['silk',         'noun',        'home',        'word', 598],
  ['leather',      'noun',        'home',        'word', 599],
  ['ivory',        'noun',        'nature',      'word', 600],

  // Food & cooking (extended)
  ['food',         'noun',        'food',        'word', 601],
  ['bread',        'noun',        'food',        'word', 602],
  ['meat',         'noun',        'food',        'word', 603],
  ['rice',         'noun',        'food',        'word', 604],
  ['milk',         'noun',        'food',        'word', 605],
  ['water',        'noun',        'food',        'word', 606],
  ['tea',          'noun',        'food',        'word', 607],
  ['sugar',        'noun',        'food',        'word', 608],
  ['salt',         'noun',        'food',        'word', 609],
  ['oil',          'noun',        'food',        'word', 610],
  ['butter',       'noun',        'food',        'word', 611],
  ['cheese',       'noun',        'food',        'word', 612],
  ['flour',        'noun',        'food',        'word', 613],
  ['wheat',        'noun',        'food',        'word', 614],
  ['corn',         'noun',        'food',        'word', 615],
  ['potato',       'noun',        'food',        'word', 616],
  ['onion',        'noun',        'food',        'word', 617],
  ['garlic',       'noun',        'food',        'word', 618],
  ['tomato',       'noun',        'food',        'word', 619],
  ['carrot',       'noun',        'food',        'word', 620],
  ['spinach',      'noun',        'food',        'word', 621],
  ['lentil',       'noun',        'food',        'word', 622],
  ['bean',         'noun',        'food',        'word', 623],
  ['apple',        'noun',        'food',        'word', 624],
  ['pear',         'noun',        'food',        'word', 625],
  ['grape',        'noun',        'food',        'word', 626],
  ['apricot',      'noun',        'food',        'word', 627],
  ['walnut',       'noun',        'food',        'word', 628],
  ['almond',       'noun',        'food',        'word', 629],
  ['mulberry',     'noun',        'food',        'word', 630],
  ['pomegranate',  'noun',        'food',        'word', 631],
  ['date (fruit)', 'noun',        'food',        'word', 632],
  ['fig',          'noun',        'food',        'word', 633],
  ['peach',        'noun',        'food',        'word', 634],
  ['plum',         'noun',        'food',        'word', 635],
  ['lemon',        'noun',        'food',        'word', 636],
  ['orange',       'noun',        'food',        'word', 637],
  ['banana',       'noun',        'food',        'word', 638],
  ['mango',        'noun',        'food',        'word', 639],
  ['honey',        'noun',        'food',        'word', 640],
  ['yoghurt',      'noun',        'food',        'word', 641],
  ['cream',        'noun',        'food',        'word', 642],
  ['soup',         'noun',        'food',        'word', 643],
  ['curry',        'noun',        'food',        'word', 644],
  ['spice',        'noun',        'food',        'word', 645],
  ['pepper',       'noun',        'food',        'word', 646],
  ['cinnamon',     'noun',        'food',        'word', 647],
  ['ginger',       'noun',        'food',        'word', 648],
  ['vinegar',      'noun',        'food',        'word', 649],
  ['cook',         'verb',        'food',        'word', 650],

  // Home & household (extended)
  ['kitchen',      'noun',        'home',        'word', 651],
  ['bedroom',      'noun',        'home',        'word', 652],
  ['bathroom',     'noun',        'home',        'word', 653],
  ['roof',         'noun',        'home',        'word', 654],
  ['wall',         'noun',        'home',        'word', 655],
  ['floor',        'noun',        'home',        'word', 656],
  ['ceiling',      'noun',        'home',        'word', 657],
  ['stair',        'noun',        'home',        'word', 658],
  ['gate',         'noun',        'home',        'word', 659],
  ['window',       'noun',        'home',        'word', 660],
  ['key',          'noun',        'home',        'word', 661],
  ['lock',         'noun',        'home',        'word', 662],
  ['lamp',         'noun',        'home',        'word', 663],
  ['candle',       'noun',        'home',        'word', 664],
  ['fire',         'noun',        'home',        'word', 665],
  ['smoke',        'noun',        'home',        'word', 666],
  ['blanket',      'noun',        'home',        'word', 667],
  ['pillow',       'noun',        'home',        'word', 668],
  ['mat',          'noun',        'home',        'word', 669],
  ['carpet',       'noun',        'home',        'word', 670],
  ['pot',          'noun',        'home',        'word', 671],
  ['pan',          'noun',        'home',        'word', 672],
  ['cup',          'noun',        'home',        'word', 673],
  ['plate',        'noun',        'home',        'word', 674],
  ['bowl',         'noun',        'home',        'word', 675],
  ['spoon',        'noun',        'home',        'word', 676],
  ['fork',         'noun',        'home',        'word', 677],
  ['knife',        'noun',        'home',        'word', 678],
  ['glass',        'noun',        'home',        'word', 679],
  ['jug',          'noun',        'home',        'word', 680],
  ['bucket',       'noun',        'home',        'word', 681],
  ['broom',        'noun',        'home',        'word', 682],
  ['cloth',        'noun',        'home',        'word', 683],
  ['needle',       'noun',        'home',        'word', 684],
  ['thread',       'noun',        'home',        'word', 685],
  ['axe',          'noun',        'home',        'word', 686],
  ['hammer',       'noun',        'home',        'word', 687],
  ['rope',         'noun',        'home',        'word', 688],
  ['bag',          'noun',        'home',        'word', 689],
  ['box',          'noun',        'home',        'word', 690],
  ['basket',       'noun',        'home',        'word', 691],
  ['cradle',       'noun',        'home',        'word', 692],
  ['garden',       'noun',        'home',        'word', 693],
  ['well',         'noun',        'home',        'word', 694],
  ['fence',        'noun',        'home',        'word', 695],
  ['barn',         'noun',        'home',        'word', 696],
  ['stable',       'noun',        'home',        'word', 697],
  ['field',        'noun',        'home',        'word', 698],
  ['wood',         'noun',        'home',        'word', 699],
  ['coal',         'noun',        'home',        'word', 700],

  // Clothing
  ['clothes',      'noun',        'clothing',    'word', 701],
  ['shirt',        'noun',        'clothing',    'word', 702],
  ['trousers',     'noun',        'clothing',    'word', 703],
  ['dress',        'noun',        'clothing',    'word', 704],
  ['coat',         'noun',        'clothing',    'word', 705],
  ['jacket',       'noun',        'clothing',    'word', 706],
  ['scarf',        'noun',        'clothing',    'word', 707],
  ['turban',       'noun',        'clothing',    'word', 708],
  ['hat',          'noun',        'clothing',    'word', 709],
  ['shoes',        'noun',        'clothing',    'word', 710],
  ['sandals',      'noun',        'clothing',    'word', 711],
  ['socks',        'noun',        'clothing',    'word', 712],
  ['belt',         'noun',        'clothing',    'word', 713],
  ['gloves',       'noun',        'clothing',    'word', 714],
  ['ring',         'noun',        'clothing',    'word', 715],
  ['necklace',     'noun',        'clothing',    'word', 716],
  ['earring',      'noun',        'clothing',    'word', 717],
  ['bracelet',     'noun',        'clothing',    'word', 718],
  ['button',       'noun',        'clothing',    'word', 719],
  ['pocket',       'noun',        'clothing',    'word', 720],

  // Work & professions
  ['work',         'noun',        'work',        'word', 721],
  ['profession',   'noun',        'work',        'word', 722],
  ['salary',       'noun',        'work',        'word', 723],
  ['employer',     'noun',        'work',        'word', 724],
  ['employee',     'noun',        'work',        'word', 725],
  ['manager',      'noun',        'work',        'word', 726],
  ['carpenter',    'noun',        'work',        'word', 727],
  ['blacksmith',   'noun',        'work',        'word', 728],
  ['weaver',       'noun',        'work',        'word', 729],
  ['shepherd',     'noun',        'work',        'word', 730],
  ['guard',        'noun',        'work',        'word', 731],
  ['cook (person)','noun',        'work',        'word', 732],
  ['tailor',       'noun',        'work',        'word', 733],
  ['barber',       'noun',        'work',        'word', 734],
  ['potter',       'noun',        'work',        'word', 735],
  ['tool',         'noun',        'work',        'word', 736],
  ['machine',      'noun',        'work',        'word', 737],
  ['factory',      'noun',        'work',        'word', 738],
  ['farm',         'noun',        'work',        'word', 739],
  ['harvest',      'noun',        'work',        'word', 740],

  // Education
  ['school',       'noun',        'education',   'word', 741],
  ['university',   'noun',        'education',   'word', 742],
  ['student',      'noun',        'education',   'word', 743],
  ['lesson',       'noun',        'education',   'word', 744],
  ['exam',         'noun',        'education',   'word', 745],
  ['pen',          'noun',        'education',   'word', 746],
  ['pencil',       'noun',        'education',   'word', 747],
  ['paper',        'noun',        'education',   'word', 748],
  ['notebook',     'noun',        'education',   'word', 749],
  ['library',      'noun',        'education',   'word', 750],
  ['language',     'noun',        'language',    'word', 751],
  ['word',         'noun',        'language',    'word', 752],
  ['sentence',     'noun',        'language',    'word', 753],
  ['meaning',      'noun',        'language',    'word', 754],
  ['translation',  'noun',        'language',    'word', 755],
  ['alphabet',     'noun',        'language',    'word', 756],
  ['letter',       'noun',        'language',    'word', 757],
  ['grammar',      'noun',        'language',    'word', 758],
  ['dictionary',   'noun',        'language',    'word', 759],
  ['story',        'noun',        'culture',     'word', 760],
  ['poem',         'noun',        'culture',     'word', 761],
  ['song',         'noun',        'culture',     'word', 762],
  ['dance',        'noun',        'culture',     'word', 763],
  ['music',        'noun',        'culture',     'word', 764],
  ['tradition',    'noun',        'culture',     'word', 765],
  ['festival',     'noun',        'culture',     'word', 766],
  ['ceremony',     'noun',        'culture',     'word', 767],
  ['prayer',       'noun',        'religion',    'word', 768],
  ['mosque',       'noun',        'religion',    'word', 769],
  ['god',          'noun',        'religion',    'word', 770],
  ['faith',        'noun',        'religion',    'word', 771],
  ['blessing',     'noun',        'religion',    'word', 772],
  ['sin',          'noun',        'religion',    'word', 773],
  ['paradise',     'noun',        'religion',    'word', 774],
  ['fast (religious)','noun',     'religion',    'word', 775],
  ['pilgrimage',   'noun',        'religion',    'word', 776],
  ['holy',         'adjective',   'religion',    'word', 777],
  ['sacrifice',    'noun',        'religion',    'word', 778],
  ['charity',      'noun',        'religion',    'word', 779],
  ['wisdom',       'noun',        'culture',     'word', 780],

  // Travel & geography (extended)
  ['road',         'noun',        'travel',      'word', 781],
  ['street',       'noun',        'travel',      'word', 782],
  ['bridge',       'noun',        'travel',      'word', 783],
  ['tunnel',       'noun',        'travel',      'word', 784],
  ['border',       'noun',        'travel',      'word', 785],
  ['village',      'noun',        'places',      'word', 786],
  ['town',         'noun',        'places',      'word', 787],
  ['capital',      'noun',        'places',      'word', 788],
  ['district',     'noun',        'places',      'word', 789],
  ['region',       'noun',        'places',      'word', 790],
  ['airport',      'noun',        'travel',      'word', 791],
  ['station',      'noun',        'travel',      'word', 792],
  ['hotel',        'noun',        'travel',      'word', 793],
  ['guest house',  'noun',        'travel',      'word', 794],
  ['restaurant',   'noun',        'travel',      'word', 795],
  ['market',       'noun',        'commerce',    'word', 796],
  ['shop',         'noun',        'commerce',    'word', 797],
  ['hospital',     'noun',        'health',      'word', 798],
  ['pharmacy',     'noun',        'health',      'word', 799],
  ['passport',     'noun',        'travel',      'word', 800],
  ['ticket',       'noun',        'travel',      'word', 801],
  ['map',          'noun',        'travel',      'word', 802],
  ['luggage',      'noun',        'travel',      'word', 803],
  ['taxi',         'noun',        'travel',      'word', 804],
  ['bus',          'noun',        'travel',      'word', 805],
  ['jeep',         'noun',        'travel',      'word', 806],
  ['helicopter',   'noun',        'travel',      'word', 807],
  ['direction',    'noun',        'travel',      'word', 808],
  ['north',        'noun',        'travel',      'word', 809],
  ['south',        'noun',        'travel',      'word', 810],
  ['east',         'noun',        'travel',      'word', 811],
  ['west',         'noun',        'travel',      'word', 812],
  ['distance',     'noun',        'travel',      'word', 813],
  ['kilometre',    'noun',        'travel',      'word', 814],
  ['path',         'noun',        'travel',      'word', 815],
  ['uphill',       'adverb',      'travel',      'word', 816],
  ['downhill',     'adverb',      'travel',      'word', 817],
  ['camp',         'noun',        'travel',      'word', 818],
  ['tent',         'noun',        'travel',      'word', 819],
  ['guide',        'noun',        'travel',      'word', 820],

  // Commerce & money
  ['price',        'noun',        'commerce',    'word', 821],
  ['cost',         'noun',        'commerce',    'word', 822],
  ['payment',      'noun',        'commerce',    'word', 823],
  ['discount',     'noun',        'commerce',    'word', 824],
  ['profit',       'noun',        'commerce',    'word', 825],
  ['loss',         'noun',        'commerce',    'word', 826],
  ['tax',          'noun',        'commerce',    'word', 827],
  ['loan',         'noun',        'commerce',    'word', 828],
  ['debt',         'noun',        'commerce',    'word', 829],
  ['receipt',      'noun',        'commerce',    'word', 830],
  ['trade',        'noun',        'commerce',    'word', 831],
  ['weight',       'noun',        'commerce',    'word', 832],
  ['kilogram',     'noun',        'commerce',    'word', 833],
  ['litre',        'noun',        'commerce',    'word', 834],
  ['metre',        'noun',        'commerce',    'word', 835],
  ['coin',         'noun',        'commerce',    'word', 836],
  ['note (money)', 'noun',        'commerce',    'word', 837],
  ['bank',         'noun',        'commerce',    'word', 838],
  ['account',      'noun',        'commerce',    'word', 839],
  ['savings',      'noun',        'commerce',    'word', 840],

  // Emotions & psychology (extended)
  ['happiness',    'noun',        'emotions',    'word', 841],
  ['sadness',      'noun',        'emotions',    'word', 842],
  ['anger',        'noun',        'emotions',    'word', 843],
  ['fear',         'noun',        'emotions',    'word', 844],
  ['hope',         'noun',        'emotions',    'word', 845],
  ['trust',        'noun',        'emotions',    'word', 846],
  ['shame',        'noun',        'emotions',    'word', 847],
  ['pride',        'noun',        'emotions',    'word', 848],
  ['jealousy',     'noun',        'emotions',    'word', 849],
  ['loneliness',   'noun',        'emotions',    'word', 850],
  ['regret',       'noun',        'emotions',    'word', 851],
  ['worry',        'noun',        'emotions',    'word', 852],
  ['patience',     'noun',        'emotions',    'word', 853],
  ['kindness',     'noun',        'emotions',    'word', 854],
  ['courage',      'noun',        'emotions',    'word', 855],
  ['respect',      'noun',        'emotions',    'word', 856],
  ['honour',       'noun',        'emotions',    'word', 857],
  ['mercy',        'noun',        'emotions',    'word', 858],
  ['peace',        'noun',        'emotions',    'word', 859],
  ['justice',      'noun',        'society',     'word', 860],

  // Colours extended
  ['colour',       'noun',        'colors',      'word', 861],
  ['red',          'adjective',   'colors',      'word', 862],
  ['blue',         'adjective',   'colors',      'word', 863],
  ['green',        'adjective',   'colors',      'word', 864],
  ['yellow',       'adjective',   'colors',      'word', 865],
  ['orange',       'adjective',   'colors',      'word', 866],
  ['pink',         'adjective',   'colors',      'word', 867],
  ['purple',       'adjective',   'colors',      'word', 868],
  ['brown',        'adjective',   'colors',      'word', 869],
  ['grey',         'adjective',   'colors',      'word', 870],
  ['golden',       'adjective',   'colors',      'word', 871],
  ['silver',       'adjective',   'colors',      'word', 872],
  ['transparent',  'adjective',   'colors',      'word', 873],
  ['colourful',    'adjective',   'colors',      'word', 874],
  ['pale',         'adjective',   'colors',      'word', 875],

  // Shapes & sizes
  ['shape',        'noun',        'geometry',    'word', 876],
  ['circle',       'noun',        'geometry',    'word', 877],
  ['square',       'noun',        'geometry',    'word', 878],
  ['triangle',     'noun',        'geometry',    'word', 879],
  ['line',         'noun',        'geometry',    'word', 880],
  ['angle',        'noun',        'geometry',    'word', 881],
  ['width',        'noun',        'geometry',    'word', 882],
  ['length',       'noun',        'geometry',    'word', 883],
  ['height',       'noun',        'geometry',    'word', 884],
  ['depth',        'noun',        'geometry',    'word', 885],
  ['size',         'noun',        'geometry',    'word', 886],
  ['heavy',        'adjective',   'adjectives',  'word', 887],
  ['light',        'adjective',   'adjectives',  'word', 888],
  ['thick',        'adjective',   'adjectives',  'word', 889],
  ['thin',         'adjective',   'adjectives',  'word', 890],
  ['narrow',       'adjective',   'adjectives',  'word', 891],
  ['wide',         'adjective',   'adjectives',  'word', 892],
  ['deep',         'adjective',   'adjectives',  'word', 893],
  ['shallow',      'adjective',   'adjectives',  'word', 894],
  ['round',        'adjective',   'adjectives',  'word', 895],
  ['flat',         'adjective',   'adjectives',  'word', 896],
  ['sharp',        'adjective',   'adjectives',  'word', 897],
  ['smooth',       'adjective',   'adjectives',  'word', 898],
  ['rough',        'adjective',   'adjectives',  'word', 899],
  ['straight',     'adjective',   'adjectives',  'word', 900],

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TIER 4  rank 901–4000  Extended vocabulary
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  // Abstract concepts
  ['idea',         'noun',        'abstract',    'word', 901],
  ['dream',        'noun',        'abstract',    'word', 902],
  ['memory',       'noun',        'abstract',    'word', 903],
  ['imagination',  'noun',        'abstract',    'word', 904],
  ['knowledge',    'noun',        'abstract',    'word', 905],
  ['truth',        'noun',        'abstract',    'word', 906],
  ['lie',          'noun',        'abstract',    'word', 907],
  ['promise',      'noun',        'abstract',    'word', 908],
  ['secret',       'noun',        'abstract',    'word', 909],
  ['opinion',      'noun',        'abstract',    'word', 910],
  ['advice',       'noun',        'abstract',    'word', 911],
  ['decision',     'noun',        'abstract',    'word', 912],
  ['plan',         'noun',        'abstract',    'word', 913],
  ['problem',      'noun',        'abstract',    'word', 914],
  ['solution',     'noun',        'abstract',    'word', 915],
  ['choice',       'noun',        'abstract',    'word', 916],
  ['chance',       'noun',        'abstract',    'word', 917],
  ['luck',         'noun',        'abstract',    'word', 918],
  ['fate',         'noun',        'abstract',    'word', 919],
  ['purpose',      'noun',        'abstract',    'word', 920],
  ['effort',       'noun',        'abstract',    'word', 921],
  ['success',      'noun',        'abstract',    'word', 922],
  ['failure',      'noun',        'abstract',    'word', 923],
  ['beginning',    'noun',        'abstract',    'word', 924],
  ['end',          'noun',        'abstract',    'word', 925],
  ['difference',   'noun',        'abstract',    'word', 926],
  ['similarity',   'noun',        'abstract',    'word', 927],
  ['example',      'noun',        'abstract',    'word', 928],
  ['type',         'noun',        'abstract',    'word', 929],
  ['amount',       'noun',        'abstract',    'word', 930],

  // Society & governance
  ['government',   'noun',        'society',     'word', 931],
  ['law',          'noun',        'society',     'word', 932],
  ['rule',         'noun',        'society',     'word', 933],
  ['right',        'noun',        'society',     'word', 934],
  ['duty',         'noun',        'society',     'word', 935],
  ['vote',         'noun',        'society',     'word', 936],
  ['election',     'noun',        'society',     'word', 937],
  ['army',         'noun',        'society',     'word', 938],
  ['conflict',     'noun',        'society',     'word', 939],
  ['peace',        'noun',        'society',     'word', 940],
  ['agreement',    'noun',        'society',     'word', 941],
  ['freedom',      'noun',        'society',     'word', 942],
  ['independence', 'noun',        'society',     'word', 943],
  ['nationality',  'noun',        'society',     'word', 944],
  ['refugee',      'noun',        'society',     'word', 945],
  ['village council','noun',      'society',     'word', 946],
  ['land',         'noun',        'society',     'word', 947],
  ['property',     'noun',        'society',     'word', 948],
  ['boundary',     'noun',        'society',     'word', 949],
  ['news',         'noun',        'society',     'word', 950],

  // Technology & modern life
  ['phone',        'noun',        'technology',  'word', 951],
  ['internet',     'noun',        'technology',  'word', 952],
  ['computer',     'noun',        'technology',  'word', 953],
  ['electricity',  'noun',        'technology',  'word', 954],
  ['television',   'noun',        'technology',  'word', 955],
  ['radio',        'noun',        'technology',  'word', 956],
  ['camera',       'noun',        'technology',  'word', 957],
  ['battery',      'noun',        'technology',  'word', 958],
  ['solar',        'adjective',   'technology',  'word', 959],
  ['signal',       'noun',        'technology',  'word', 960],
  ['message',      'noun',        'technology',  'word', 961],
  ['network',      'noun',        'technology',  'word', 962],
  ['generator',    'noun',        'technology',  'word', 963],
  ['engine',       'noun',        'technology',  'word', 964],
  ['wheel',        'noun',        'technology',  'word', 965],
  ['fuel',         'noun',        'technology',  'word', 966],
  ['pump',         'noun',        'technology',  'word', 967],
  ['pipe',         'noun',        'technology',  'word', 968],
  ['wire',         'noun',        'technology',  'word', 969],
  ['switch',       'noun',        'technology',  'word', 970],

  // Health extended
  ['hospital',     'noun',        'health',      'word', 971],
  ['clinic',       'noun',        'health',      'word', 972],
  ['dentist',      'noun',        'health',      'word', 973],
  ['wound',        'noun',        'health',      'word', 974],
  ['bandage',      'noun',        'health',      'word', 975],
  ['tablet',       'noun',        'health',      'word', 976],
  ['injection',    'noun',        'health',      'word', 977],
  ['surgery',      'noun',        'health',      'word', 978],
  ['pregnant',     'adjective',   'health',      'word', 979],
  ['birth',        'noun',        'health',      'word', 980],
  ['death',        'noun',        'health',      'word', 981],
  ['healthy',      'adjective',   'health',      'word', 982],
  ['sick',         'adjective',   'health',      'word', 983],
  ['weak',         'adjective',   'health',      'word', 984],
  ['strong',       'adjective',   'health',      'word', 985],
  ['blind',        'adjective',   'health',      'word', 986],
  ['deaf',         'adjective',   'health',      'word', 987],
  ['dizzy',        'adjective',   'health',      'word', 988],
  ['nausea',       'noun',        'health',      'word', 989],
  ['rash',         'noun',        'health',      'word', 990],

  // Extended verbs
  ['eat',          'verb',        'verbs',       'word',  991],
  ['drink',        'verb',        'verbs',       'word',  992],
  ['sleep',        'verb',        'verbs',       'word',  993],
  ['wake up',      'verb',        'verbs',       'word',  994],
  ['wash',         'verb',        'verbs',       'word',  995],
  ['clean',        'verb',        'verbs',       'word',  996],
  ['sweep',        'verb',        'verbs',       'word',  997],
  ['lift',         'verb',        'verbs',       'word',  998],
  ['throw',        'verb',        'verbs',       'word',  999],
  ['catch',        'verb',        'verbs',       'word', 1000],
  ['dig',          'verb',        'verbs',       'word', 1001],
  ['plant',        'verb',        'verbs',       'word', 1002],
  ['harvest',      'verb',        'verbs',       'word', 1003],
  ['graze',        'verb',        'verbs',       'word', 1004],
  ['hunt',         'verb',        'verbs',       'word', 1005],
  ['fish',         'verb',        'verbs',       'word', 1006],
  ['climb',        'verb',        'verbs',       'word', 1007],
  ['swim',         'verb',        'verbs',       'word', 1008],
  ['jump',         'verb',        'verbs',       'word', 1009],
  ['fly',          'verb',        'verbs',       'word', 1010],
  ['sing',         'verb',        'verbs',       'word', 1011],
  ['dance',        'verb',        'verbs',       'word', 1012],
  ['laugh',        'verb',        'verbs',       'word', 1013],
  ['cry',          'verb',        'verbs',       'word', 1014],
  ['shout',        'verb',        'verbs',       'word', 1015],
  ['whisper',      'verb',        'verbs',       'word', 1016],
  ['pray',         'verb',        'verbs',       'word', 1017],
  ['greet',        'verb',        'verbs',       'word', 1018],
  ['invite',       'verb',        'verbs',       'word', 1019],
  ['celebrate',    'verb',        'verbs',       'word', 1020],
  ['punish',       'verb',        'verbs',       'word', 1021],
  ['forgive',      'verb',        'verbs',       'word', 1022],
  ['escape',       'verb',        'verbs',       'word', 1023],
  ['rescue',       'verb',        'verbs',       'word', 1024],
  ['wake',         'verb',        'verbs',       'word', 1025],
  ['rest',         'verb',        'verbs',       'word', 1026],
  ['breathe',      'verb',        'verbs',       'word', 1027],
  ['bleed',        'verb',        'verbs',       'word', 1028],
  ['heal',         'verb',        'verbs',       'word', 1029],
  ['burn',         'verb',        'verbs',       'word', 1030],
  ['freeze',       'verb',        'verbs',       'word', 1031],
  ['melt',         'verb',        'verbs',       'word', 1032],
  ['mix',          'verb',        'verbs',       'word', 1033],
  ['pour',         'verb',        'verbs',       'word', 1034],
  ['tie',          'verb',        'verbs',       'word', 1035],
  ['untie',        'verb',        'verbs',       'word', 1036],
  ['weigh',        'verb',        'verbs',       'word', 1037],
  ['count',        'verb',        'verbs',       'word', 1038],
  ['measure',      'verb',        'verbs',       'word', 1039],
  ['compare',      'verb',        'verbs',       'word', 1040],

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // Common phrases  (rank 1100+)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ['good morning',               'phrase', 'greetings',  'phrase', 1100],
  ['good afternoon',             'phrase', 'greetings',  'phrase', 1101],
  ['good evening',               'phrase', 'greetings',  'phrase', 1102],
  ['good night',                 'phrase', 'greetings',  'phrase', 1103],
  ['see you later',              'phrase', 'greetings',  'phrase', 1104],
  ['see you tomorrow',           'phrase', 'greetings',  'phrase', 1105],
  ['take care',                  'phrase', 'greetings',  'phrase', 1106],
  ['how is your family',         'phrase', 'greetings',  'phrase', 1107],
  ['welcome to our home',        'phrase', 'greetings',  'phrase', 1108],
  ['please sit down',            'phrase', 'greetings',  'phrase', 1109],
  ['have you eaten',             'phrase', 'food',       'phrase', 1110],
  ['do you want tea',            'phrase', 'food',       'phrase', 1111],
  ['the food is ready',          'phrase', 'food',       'phrase', 1112],
  ['it tastes good',             'phrase', 'food',       'phrase', 1113],
  ['I am full thank you',        'phrase', 'food',       'phrase', 1114],
  ['I am allergic to this',      'phrase', 'food',       'phrase', 1115],
  ['is this halal',              'phrase', 'food',       'phrase', 1116],
  ['I need to rest',             'phrase', 'health',     'phrase', 1117],
  ['I feel better now',          'phrase', 'health',     'phrase', 1118],
  ['where does it hurt',         'phrase', 'health',     'phrase', 1119],
  ['I have been sick for days',  'phrase', 'health',     'phrase', 1120],
  ['I cannot sleep',             'phrase', 'health',     'phrase', 1121],
  ['take this medicine',         'phrase', 'health',     'phrase', 1122],
  ['how far is the village',     'phrase', 'travel',     'phrase', 1123],
  ['the road is blocked',        'phrase', 'travel',     'phrase', 1124],
  ['there is no signal here',    'phrase', 'travel',     'phrase', 1125],
  ['we are going to hunt',       'phrase', 'travel',     'phrase', 1126],
  ['the pass is closed in winter','phrase','travel',     'phrase', 1127],
  ['I am from the city',         'phrase', 'travel',     'phrase', 1128],
  ['I have never been here',     'phrase', 'travel',     'phrase', 1129],
  ['this village is beautiful',  'phrase', 'travel',     'phrase', 1130],
  ['I want to stay here',        'phrase', 'travel',     'phrase', 1131],
  ['how many people live here',  'phrase', 'places',     'phrase', 1132],
  ['what language do they speak','phrase', 'language',   'phrase', 1133],
  ['I want to learn your language','phrase','language',  'phrase', 1134],
  ['say it again please',        'phrase', 'language',   'phrase', 1135],
  ['how do you write this',      'phrase', 'language',   'phrase', 1136],
  ['what does this mean',        'phrase', 'language',   'phrase', 1137],
  ['is there a school here',     'phrase', 'education',  'phrase', 1138],
  ['children go to school here', 'phrase', 'education',  'phrase', 1139],
  ['I went to university',       'phrase', 'education',  'phrase', 1140],
  ['I am studying',              'phrase', 'education',  'phrase', 1141],
  ['what is your profession',    'phrase', 'work',       'phrase', 1142],
  ['I am a farmer',              'phrase', 'work',       'phrase', 1143],
  ['I am a shepherd',            'phrase', 'work',       'phrase', 1144],
  ['the harvest was good',       'phrase', 'work',       'phrase', 1145],
  ['the harvest was bad',        'phrase', 'work',       'phrase', 1146],
  ['the glacier is melting',     'phrase', 'nature',     'phrase', 1147],
  ['there was a landslide',      'phrase', 'nature',     'phrase', 1148],
  ['the river is rising',        'phrase', 'nature',     'phrase', 1149],
  ['it will rain tomorrow',      'phrase', 'nature',     'phrase', 1150],
  ['the winter is harsh this year','phrase','nature',    'phrase', 1151],
  ['the flowers are blooming',   'phrase', 'nature',     'phrase', 1152],
  ['congratulations on your wedding','phrase','social',  'phrase', 1153],
  ['I am sorry for your loss',   'phrase', 'social',     'phrase', 1154],
  ['God willing we will meet again','phrase','religion', 'phrase', 1155],
  ['I will pray for you',        'phrase', 'religion',   'phrase', 1156],
  ['it is God\'s will',          'phrase', 'religion',   'phrase', 1157],
  ['happy Eid',                  'phrase', 'religion',   'phrase', 1158],
  ['blessed Ramadan',            'phrase', 'religion',   'phrase', 1159],
  ['I am fasting today',         'phrase', 'religion',   'phrase', 1160],
  ['we had a wedding yesterday', 'phrase', 'social',     'phrase', 1161],
  ['bring the children',         'phrase', 'family',     'phrase', 1162],
  ['the elder has spoken',       'phrase', 'society',    'phrase', 1163],
  ['we respect our traditions',  'phrase', 'culture',    'phrase', 1164],
  ['this is our custom',         'phrase', 'culture',    'phrase', 1165],
  ['tell me a story',            'phrase', 'culture',    'phrase', 1166],
  ['sing us a song',             'phrase', 'culture',    'phrase', 1167],
  ['I remember that story',      'phrase', 'culture',    'phrase', 1168],
  ['how much do you earn',       'phrase', 'commerce',   'phrase', 1169],
  ['the price is too high',      'phrase', 'commerce',   'phrase', 1170],
  ['can you give a discount',    'phrase', 'commerce',   'phrase', 1171],
  ['do you accept cash',         'phrase', 'commerce',   'phrase', 1172],
  ['I do not have change',       'phrase', 'commerce',   'phrase', 1173],
  ['this is broken',             'phrase', 'home',       'phrase', 1174],
  ['can you fix this',           'phrase', 'home',       'phrase', 1175],
  ['the water is cut off',       'phrase', 'home',       'phrase', 1176],
  ['the electricity is gone',    'phrase', 'home',       'phrase', 1177],
  ['keep the door closed',       'phrase', 'home',       'phrase', 1178],
  ['the dog is friendly',        'phrase', 'animals',    'phrase', 1179],
  ['the dog will bite',          'phrase', 'animals',    'phrase', 1180],
  ['the animals need water',     'phrase', 'animals',    'phrase', 1181],
  ['I am afraid of snakes',      'phrase', 'animals',    'phrase', 1182],
  ['the eagle is flying',        'phrase', 'animals',    'phrase', 1183],

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TIER 5  rank 2000+  Less frequent but valuable
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ['agriculture',  'noun',        'work',        'word', 2001],
  ['irrigation',   'noun',        'work',        'word', 2002],
  ['terraced field','noun',       'work',        'word', 2003],
  ['apricot orchard','noun',      'work',        'word', 2004],
  ['shepherd',     'noun',        'work',        'word', 2005],
  ['pasture',      'noun',        'work',        'word', 2006],
  ['transhumance', 'noun',        'work',        'word', 2007],
  ['firewood',     'noun',        'home',        'word', 2008],
  ['dung',         'noun',        'home',        'word', 2009],
  ['spring (water)','noun',       'nature',      'word', 2010],
  ['spring season','noun',        'time',        'word', 2011],
  ['autumn season','noun',        'time',        'word', 2012],
  ['summer season','noun',        'time',        'word', 2013],
  ['winter season','noun',        'time',        'word', 2014],
  ['noon',         'noun',        'time',        'word', 2015],
  ['dusk',         'noun',        'time',        'word', 2016],
  ['dawn',         'noun',        'time',        'word', 2017],
  ['yesterday',    'adverb',      'time',        'word', 2018],
  ['today',        'adverb',      'time',        'word', 2019],
  ['tomorrow',     'adverb',      'time',        'word', 2020],
  ['last year',    'phrase',      'time',        'phrase',2021],
  ['next year',    'phrase',      'time',        'phrase',2022],
  ['long ago',     'phrase',      'time',        'phrase',2023],
  ['recently',     'adverb',      'time',        'word', 2024],
  ['forever',      'adverb',      'time',        'word', 2025],
  ['century',      'noun',        'time',        'word', 2026],
  ['generation',   'noun',        'time',        'word', 2027],
  ['era',          'noun',        'time',        'word', 2028],
  ['anniversary',  'noun',        'time',        'word', 2029],
  ['calendar',     'noun',        'time',        'word', 2030],
  ['mineral',      'noun',        'nature',      'word', 2031],
  ['gemstone',     'noun',        'nature',      'word', 2032],
  ['ruby',         'noun',        'nature',      'word', 2033],
  ['emerald',      'noun',        'nature',      'word', 2034],
  ['heritage',     'noun',        'culture',     'word', 2035],
  ['legend',       'noun',        'culture',     'word', 2036],
  ['proverb',      'noun',        'culture',     'word', 2037],
  ['riddle',       'noun',        'culture',     'word', 2038],
  ['instrument',   'noun',        'culture',     'word', 2039],
  ['flute',        'noun',        'culture',     'word', 2040],
  ['drum',         'noun',        'culture',     'word', 2041],
  ['sitar',        'noun',        'culture',     'word', 2042],
  ['embroidery',   'noun',        'culture',     'word', 2043],
  ['handicraft',   'noun',        'culture',     'word', 2044],
  ['carpet',       'noun',        'culture',     'word', 2045],
  ['shawl',        'noun',        'clothing',    'word', 2046],
  ['shalwar',      'noun',        'clothing',    'word', 2047],
  ['kameez',       'noun',        'clothing',    'word', 2048],
  ['dupatta',      'noun',        'clothing',    'word', 2049],
  ['waistcoat',    'noun',        'clothing',    'word', 2050],
  ['cloak',        'noun',        'clothing',    'word', 2051],
  ['turban',       'noun',        'clothing',    'word', 2052],
  ['tribe',        'noun',        'society',     'word', 2053],
  ['clan',         'noun',        'society',     'word', 2054],
  ['chief',        'noun',        'society',     'word', 2055],
  ['council',      'noun',        'society',     'word', 2056],
  ['agreement',    'noun',        'society',     'word', 2057],
  ['dispute',      'noun',        'society',     'word', 2058],
  ['mediation',    'noun',        'society',     'word', 2059],
  ['punishment',   'noun',        'society',     'word', 2060],
  ['reward',       'noun',        'society',     'word', 2061],
  ['orphan',       'noun',        'society',     'word', 2062],
  ['widow',        'noun',        'society',     'word', 2063],
  ['migrant',      'noun',        'society',     'word', 2064],
  ['diaspora',     'noun',        'society',     'word', 2065],
  ['literacy',     'noun',        'education',   'word', 2066],
  ['script',       'noun',        'language',    'word', 2067],
  ['dialect',      'noun',        'language',    'word', 2068],
  ['accent',       'noun',        'language',    'word', 2069],
  ['bilingual',    'adjective',   'language',    'word', 2070],
  ['oral tradition','noun',       'language',    'word', 2071],
  ['endangered language','phrase','language',   'phrase',2072],
  ['mother tongue','noun',        'language',    'word', 2073],
  ['loanword',     'noun',        'language',    'word', 2074],
  ['verb',         'noun',        'language',    'word', 2075],
  ['noun',         'noun',        'language',    'word', 2076],
  ['adjective',    'noun',        'language',    'word', 2077],
  ['plural',       'noun',        'language',    'word', 2078],
  ['singular',     'noun',        'language',    'word', 2079],
  ['tense',        'noun',        'language',    'word', 2080],
];

let added = 0;
const newEntries = [];
for (const [en, pos, category, type, rank] of WORDS) {
  const entry = add(en, pos, category, type, rank);
  if (entry) { newEntries.push(entry); added++; }
}

// Insert sorted by frequency_rank so queue naturally shows most-needed first
lex.entries.push(...newEntries);
lex.entries.sort((a, b) => (a.frequency_rank || 9999) - (b.frequency_rank || 9999));

lex.updated_at    = new Date().toISOString().slice(0, 10);
lex.total_entries = lex.entries.length;
lex.verified_bsk  = lex.entries.filter(e => e.translations?.bsk?.verified).length;
lex.pending_bsk   = lex.entries.filter(e => !e.translations?.bsk).length;

fs.writeFileSync(LEXICON_FILE, JSON.stringify(lex, null, 2), 'utf8');
console.log(`Added   : ${added} new entries`);
console.log(`Total   : ${lex.total_entries}`);
console.log(`Verified BSK : ${lex.verified_bsk}`);
console.log(`Pending BSK  : ${lex.pending_bsk}`);
